// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: game_engine/common/v1/enums.proto

// Protobuf Java Version: 3.25.1
package com.game_engine.common.v1;

/**
 * <pre>
 * Device type
 * </pre>
 *
 * Protobuf enum {@code game_engine.common.v1.DeviceType}
 */
public enum DeviceType
    implements com.google.protobuf.ProtocolMessageEnum {
  /**
   * <code>DEVICE_TYPE_UNSPECIFIED = 0;</code>
   */
  DEVICE_TYPE_UNSPECIFIED(0),
  /**
   * <code>DEVICE_TYPE_DESKTOP = 1;</code>
   */
  DEVICE_TYPE_DESKTOP(1),
  /**
   * <code>DEVICE_TYPE_MOBILE = 2;</code>
   */
  DEVICE_TYPE_MOBILE(2),
  /**
   * <code>DEVICE_TYPE_TABLET = 3;</code>
   */
  DEVICE_TYPE_TABLET(3),
  /**
   * <code>DEVICE_TYPE_TV = 4;</code>
   */
  DEVICE_TYPE_TV(4),
  /**
   * <code>DEVICE_TYPE_WATCH = 5;</code>
   */
  DEVICE_TYPE_WATCH(5),
  /**
   * <code>DEVICE_TYPE_VR = 6;</code>
   */
  DEVICE_TYPE_VR(6),
  /**
   * <code>DEVICE_TYPE_CONSOLE = 7;</code>
   */
  DEVICE_TYPE_CONSOLE(7),
  UNRECOGNIZED(-1),
  ;

  /**
   * <code>DEVICE_TYPE_UNSPECIFIED = 0;</code>
   */
  public static final int DEVICE_TYPE_UNSPECIFIED_VALUE = 0;
  /**
   * <code>DEVICE_TYPE_DESKTOP = 1;</code>
   */
  public static final int DEVICE_TYPE_DESKTOP_VALUE = 1;
  /**
   * <code>DEVICE_TYPE_MOBILE = 2;</code>
   */
  public static final int DEVICE_TYPE_MOBILE_VALUE = 2;
  /**
   * <code>DEVICE_TYPE_TABLET = 3;</code>
   */
  public static final int DEVICE_TYPE_TABLET_VALUE = 3;
  /**
   * <code>DEVICE_TYPE_TV = 4;</code>
   */
  public static final int DEVICE_TYPE_TV_VALUE = 4;
  /**
   * <code>DEVICE_TYPE_WATCH = 5;</code>
   */
  public static final int DEVICE_TYPE_WATCH_VALUE = 5;
  /**
   * <code>DEVICE_TYPE_VR = 6;</code>
   */
  public static final int DEVICE_TYPE_VR_VALUE = 6;
  /**
   * <code>DEVICE_TYPE_CONSOLE = 7;</code>
   */
  public static final int DEVICE_TYPE_CONSOLE_VALUE = 7;


  public final int getNumber() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalArgumentException(
          "Can't get the number of an unknown enum value.");
    }
    return value;
  }

  /**
   * @param value The numeric wire value of the corresponding enum entry.
   * @return The enum associated with the given numeric wire value.
   * @deprecated Use {@link #forNumber(int)} instead.
   */
  @java.lang.Deprecated
  public static DeviceType valueOf(int value) {
    return forNumber(value);
  }

  /**
   * @param value The numeric wire value of the corresponding enum entry.
   * @return The enum associated with the given numeric wire value.
   */
  public static DeviceType forNumber(int value) {
    switch (value) {
      case 0: return DEVICE_TYPE_UNSPECIFIED;
      case 1: return DEVICE_TYPE_DESKTOP;
      case 2: return DEVICE_TYPE_MOBILE;
      case 3: return DEVICE_TYPE_TABLET;
      case 4: return DEVICE_TYPE_TV;
      case 5: return DEVICE_TYPE_WATCH;
      case 6: return DEVICE_TYPE_VR;
      case 7: return DEVICE_TYPE_CONSOLE;
      default: return null;
    }
  }

  public static com.google.protobuf.Internal.EnumLiteMap<DeviceType>
      internalGetValueMap() {
    return internalValueMap;
  }
  private static final com.google.protobuf.Internal.EnumLiteMap<
      DeviceType> internalValueMap =
        new com.google.protobuf.Internal.EnumLiteMap<DeviceType>() {
          public DeviceType findValueByNumber(int number) {
            return DeviceType.forNumber(number);
          }
        };

  public final com.google.protobuf.Descriptors.EnumValueDescriptor
      getValueDescriptor() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalStateException(
          "Can't get the descriptor of an unrecognized enum value.");
    }
    return getDescriptor().getValues().get(ordinal());
  }
  public final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptorForType() {
    return getDescriptor();
  }
  public static final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptor() {
    return com.game_engine.common.v1.Enums.getDescriptor().getEnumTypes().get(9);
  }

  private static final DeviceType[] VALUES = values();

  public static DeviceType valueOf(
      com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
    if (desc.getType() != getDescriptor()) {
      throw new java.lang.IllegalArgumentException(
        "EnumValueDescriptor is not for this type.");
    }
    if (desc.getIndex() == -1) {
      return UNRECOGNIZED;
    }
    return VALUES[desc.getIndex()];
  }

  private final int value;

  private DeviceType(int value) {
    this.value = value;
  }

  // @@protoc_insertion_point(enum_scope:game_engine.common.v1.DeviceType)
}

