// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: game_engine/risk/v1/risk_service.proto

// Protobuf Java Version: 3.25.1
package com.game_engine.risk.v1;

public interface GetRiskScoreResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:game_engine.risk.v1.GetRiskScoreResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string user_id = 1;</code>
   * @return The userId.
   */
  java.lang.String getUserId();
  /**
   * <code>string user_id = 1;</code>
   * @return The bytes for userId.
   */
  com.google.protobuf.ByteString
      getUserIdBytes();

  /**
   * <code>int32 score = 2;</code>
   * @return The score.
   */
  int getScore();

  /**
   * <code>string risk_level = 3;</code>
   * @return The riskLevel.
   */
  java.lang.String getRiskLevel();
  /**
   * <code>string risk_level = 3;</code>
   * @return The bytes for riskLevel.
   */
  com.google.protobuf.ByteString
      getRiskLevelBytes();
}
