FROM golang:1.21-alpine AS builder
WORKDIR /app
COPY go.mod go.sum ./
RUN go mod download
COPY common/ ./common/
COPY player/ ./player/
WORKDIR /app/player
RUN CGO_ENABLED=0 GOOS=linux go build -o /gateway-player .

FROM alpine:3.19
RUN apk --no-cache add ca-certificates tzdata
WORKDIR /app
COPY --from=builder /gateway-player .
COPY player/configs ./configs
EXPOSE 8080
CMD ["./gateway-player"]
