platform :ios, '15.0'
use_frameworks!
inhibit_all_warnings!

target 'CasinoGame' do
  # Networking
  pod 'Alamofire', '~> 5.8'
  pod 'Starscream', '~> 4.0'
  
  # UI
  pod 'SnapKit', '~> 5.6'
  pod 'Kingfisher', '~> 7.10'
  
  # Utilities
  pod 'KeychainAccess', '~> 4.2'
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '15.0'
    end
  end
end
