// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: game_engine/bonus/v1/bonus_service.proto

// Protobuf Java Version: 3.25.1
package com.game_engine.bonus.v1;

public interface CreateRebetClaimResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:game_engine.bonus.v1.CreateRebetClaimResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string rebet_id = 1;</code>
   * @return The rebetId.
   */
  java.lang.String getRebetId();
  /**
   * <code>string rebet_id = 1;</code>
   * @return The bytes for rebetId.
   */
  com.google.protobuf.ByteString
      getRebetIdBytes();

  /**
   * <code>string status = 2;</code>
   * @return The status.
   */
  java.lang.String getStatus();
  /**
   * <code>string status = 2;</code>
   * @return The bytes for status.
   */
  com.google.protobuf.ByteString
      getStatusBytes();

  /**
   * <code>double current_rebet = 3;</code>
   * @return The currentRebet.
   */
  double getCurrentRebet();
}
