// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: commission/v1/commission_service.proto

// Protobuf Java Version: 3.25.3
package com.game_engine.commission.v1;

/**
 * Protobuf type {@code game_engine.commission.v1.GetCommissionClaimByIdResponse}
 */
public final class GetCommissionClaimByIdResponse extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:game_engine.commission.v1.GetCommissionClaimByIdResponse)
    GetCommissionClaimByIdResponseOrBuilder {
private static final long serialVersionUID = 0L;
  // Use GetCommissionClaimByIdResponse.newBuilder() to construct.
  private GetCommissionClaimByIdResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private GetCommissionClaimByIdResponse() {
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new GetCommissionClaimByIdResponse();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.game_engine.commission.v1.CommissionServiceOuterClass.internal_static_game_engine_commission_v1_GetCommissionClaimByIdResponse_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.game_engine.commission.v1.CommissionServiceOuterClass.internal_static_game_engine_commission_v1_GetCommissionClaimByIdResponse_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.game_engine.commission.v1.GetCommissionClaimByIdResponse.class, com.game_engine.commission.v1.GetCommissionClaimByIdResponse.Builder.class);
  }

  private int bitField0_;
  public static final int CLAIM_FIELD_NUMBER = 1;
  private com.game_engine.commission.v1.CommissionClaimMsg claim_;
  /**
   * <code>.game_engine.commission.v1.CommissionClaimMsg claim = 1 [json_name = "claim"];</code>
   * @return Whether the claim field is set.
   */
  @java.lang.Override
  public boolean hasClaim() {
    return ((bitField0_ & 0x00000001) != 0);
  }
  /**
   * <code>.game_engine.commission.v1.CommissionClaimMsg claim = 1 [json_name = "claim"];</code>
   * @return The claim.
   */
  @java.lang.Override
  public com.game_engine.commission.v1.CommissionClaimMsg getClaim() {
    return claim_ == null ? com.game_engine.commission.v1.CommissionClaimMsg.getDefaultInstance() : claim_;
  }
  /**
   * <code>.game_engine.commission.v1.CommissionClaimMsg claim = 1 [json_name = "claim"];</code>
   */
  @java.lang.Override
  public com.game_engine.commission.v1.CommissionClaimMsgOrBuilder getClaimOrBuilder() {
    return claim_ == null ? com.game_engine.commission.v1.CommissionClaimMsg.getDefaultInstance() : claim_;
  }

  public static final int FOUND_FIELD_NUMBER = 2;
  private boolean found_ = false;
  /**
   * <code>bool found = 2 [json_name = "found"];</code>
   * @return The found.
   */
  @java.lang.Override
  public boolean getFound() {
    return found_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (((bitField0_ & 0x00000001) != 0)) {
      output.writeMessage(1, getClaim());
    }
    if (found_ != false) {
      output.writeBool(2, found_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (((bitField0_ & 0x00000001) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, getClaim());
    }
    if (found_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(2, found_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.game_engine.commission.v1.GetCommissionClaimByIdResponse)) {
      return super.equals(obj);
    }
    com.game_engine.commission.v1.GetCommissionClaimByIdResponse other = (com.game_engine.commission.v1.GetCommissionClaimByIdResponse) obj;

    if (hasClaim() != other.hasClaim()) return false;
    if (hasClaim()) {
      if (!getClaim()
          .equals(other.getClaim())) return false;
    }
    if (getFound()
        != other.getFound()) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasClaim()) {
      hash = (37 * hash) + CLAIM_FIELD_NUMBER;
      hash = (53 * hash) + getClaim().hashCode();
    }
    hash = (37 * hash) + FOUND_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
        getFound());
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.game_engine.commission.v1.GetCommissionClaimByIdResponse parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.game_engine.commission.v1.GetCommissionClaimByIdResponse parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.game_engine.commission.v1.GetCommissionClaimByIdResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.game_engine.commission.v1.GetCommissionClaimByIdResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.game_engine.commission.v1.GetCommissionClaimByIdResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.game_engine.commission.v1.GetCommissionClaimByIdResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.game_engine.commission.v1.GetCommissionClaimByIdResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.game_engine.commission.v1.GetCommissionClaimByIdResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static com.game_engine.commission.v1.GetCommissionClaimByIdResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static com.game_engine.commission.v1.GetCommissionClaimByIdResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.game_engine.commission.v1.GetCommissionClaimByIdResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.game_engine.commission.v1.GetCommissionClaimByIdResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.game_engine.commission.v1.GetCommissionClaimByIdResponse prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code game_engine.commission.v1.GetCommissionClaimByIdResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:game_engine.commission.v1.GetCommissionClaimByIdResponse)
      com.game_engine.commission.v1.GetCommissionClaimByIdResponseOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.game_engine.commission.v1.CommissionServiceOuterClass.internal_static_game_engine_commission_v1_GetCommissionClaimByIdResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.game_engine.commission.v1.CommissionServiceOuterClass.internal_static_game_engine_commission_v1_GetCommissionClaimByIdResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.game_engine.commission.v1.GetCommissionClaimByIdResponse.class, com.game_engine.commission.v1.GetCommissionClaimByIdResponse.Builder.class);
    }

    // Construct using com.game_engine.commission.v1.GetCommissionClaimByIdResponse.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getClaimFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      claim_ = null;
      if (claimBuilder_ != null) {
        claimBuilder_.dispose();
        claimBuilder_ = null;
      }
      found_ = false;
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.game_engine.commission.v1.CommissionServiceOuterClass.internal_static_game_engine_commission_v1_GetCommissionClaimByIdResponse_descriptor;
    }

    @java.lang.Override
    public com.game_engine.commission.v1.GetCommissionClaimByIdResponse getDefaultInstanceForType() {
      return com.game_engine.commission.v1.GetCommissionClaimByIdResponse.getDefaultInstance();
    }

    @java.lang.Override
    public com.game_engine.commission.v1.GetCommissionClaimByIdResponse build() {
      com.game_engine.commission.v1.GetCommissionClaimByIdResponse result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.game_engine.commission.v1.GetCommissionClaimByIdResponse buildPartial() {
      com.game_engine.commission.v1.GetCommissionClaimByIdResponse result = new com.game_engine.commission.v1.GetCommissionClaimByIdResponse(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(com.game_engine.commission.v1.GetCommissionClaimByIdResponse result) {
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.claim_ = claimBuilder_ == null
            ? claim_
            : claimBuilder_.build();
        to_bitField0_ |= 0x00000001;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.found_ = found_;
      }
      result.bitField0_ |= to_bitField0_;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.game_engine.commission.v1.GetCommissionClaimByIdResponse) {
        return mergeFrom((com.game_engine.commission.v1.GetCommissionClaimByIdResponse)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.game_engine.commission.v1.GetCommissionClaimByIdResponse other) {
      if (other == com.game_engine.commission.v1.GetCommissionClaimByIdResponse.getDefaultInstance()) return this;
      if (other.hasClaim()) {
        mergeClaim(other.getClaim());
      }
      if (other.getFound() != false) {
        setFound(other.getFound());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              input.readMessage(
                  getClaimFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            case 16: {
              found_ = input.readBool();
              bitField0_ |= 0x00000002;
              break;
            } // case 16
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private com.game_engine.commission.v1.CommissionClaimMsg claim_;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.game_engine.commission.v1.CommissionClaimMsg, com.game_engine.commission.v1.CommissionClaimMsg.Builder, com.game_engine.commission.v1.CommissionClaimMsgOrBuilder> claimBuilder_;
    /**
     * <code>.game_engine.commission.v1.CommissionClaimMsg claim = 1 [json_name = "claim"];</code>
     * @return Whether the claim field is set.
     */
    public boolean hasClaim() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>.game_engine.commission.v1.CommissionClaimMsg claim = 1 [json_name = "claim"];</code>
     * @return The claim.
     */
    public com.game_engine.commission.v1.CommissionClaimMsg getClaim() {
      if (claimBuilder_ == null) {
        return claim_ == null ? com.game_engine.commission.v1.CommissionClaimMsg.getDefaultInstance() : claim_;
      } else {
        return claimBuilder_.getMessage();
      }
    }
    /**
     * <code>.game_engine.commission.v1.CommissionClaimMsg claim = 1 [json_name = "claim"];</code>
     */
    public Builder setClaim(com.game_engine.commission.v1.CommissionClaimMsg value) {
      if (claimBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        claim_ = value;
      } else {
        claimBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>.game_engine.commission.v1.CommissionClaimMsg claim = 1 [json_name = "claim"];</code>
     */
    public Builder setClaim(
        com.game_engine.commission.v1.CommissionClaimMsg.Builder builderForValue) {
      if (claimBuilder_ == null) {
        claim_ = builderForValue.build();
      } else {
        claimBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>.game_engine.commission.v1.CommissionClaimMsg claim = 1 [json_name = "claim"];</code>
     */
    public Builder mergeClaim(com.game_engine.commission.v1.CommissionClaimMsg value) {
      if (claimBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0) &&
          claim_ != null &&
          claim_ != com.game_engine.commission.v1.CommissionClaimMsg.getDefaultInstance()) {
          getClaimBuilder().mergeFrom(value);
        } else {
          claim_ = value;
        }
      } else {
        claimBuilder_.mergeFrom(value);
      }
      if (claim_ != null) {
        bitField0_ |= 0x00000001;
        onChanged();
      }
      return this;
    }
    /**
     * <code>.game_engine.commission.v1.CommissionClaimMsg claim = 1 [json_name = "claim"];</code>
     */
    public Builder clearClaim() {
      bitField0_ = (bitField0_ & ~0x00000001);
      claim_ = null;
      if (claimBuilder_ != null) {
        claimBuilder_.dispose();
        claimBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <code>.game_engine.commission.v1.CommissionClaimMsg claim = 1 [json_name = "claim"];</code>
     */
    public com.game_engine.commission.v1.CommissionClaimMsg.Builder getClaimBuilder() {
      bitField0_ |= 0x00000001;
      onChanged();
      return getClaimFieldBuilder().getBuilder();
    }
    /**
     * <code>.game_engine.commission.v1.CommissionClaimMsg claim = 1 [json_name = "claim"];</code>
     */
    public com.game_engine.commission.v1.CommissionClaimMsgOrBuilder getClaimOrBuilder() {
      if (claimBuilder_ != null) {
        return claimBuilder_.getMessageOrBuilder();
      } else {
        return claim_ == null ?
            com.game_engine.commission.v1.CommissionClaimMsg.getDefaultInstance() : claim_;
      }
    }
    /**
     * <code>.game_engine.commission.v1.CommissionClaimMsg claim = 1 [json_name = "claim"];</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.game_engine.commission.v1.CommissionClaimMsg, com.game_engine.commission.v1.CommissionClaimMsg.Builder, com.game_engine.commission.v1.CommissionClaimMsgOrBuilder> 
        getClaimFieldBuilder() {
      if (claimBuilder_ == null) {
        claimBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.game_engine.commission.v1.CommissionClaimMsg, com.game_engine.commission.v1.CommissionClaimMsg.Builder, com.game_engine.commission.v1.CommissionClaimMsgOrBuilder>(
                getClaim(),
                getParentForChildren(),
                isClean());
        claim_ = null;
      }
      return claimBuilder_;
    }

    private boolean found_ ;
    /**
     * <code>bool found = 2 [json_name = "found"];</code>
     * @return The found.
     */
    @java.lang.Override
    public boolean getFound() {
      return found_;
    }
    /**
     * <code>bool found = 2 [json_name = "found"];</code>
     * @param value The found to set.
     * @return This builder for chaining.
     */
    public Builder setFound(boolean value) {

      found_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>bool found = 2 [json_name = "found"];</code>
     * @return This builder for chaining.
     */
    public Builder clearFound() {
      bitField0_ = (bitField0_ & ~0x00000002);
      found_ = false;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:game_engine.commission.v1.GetCommissionClaimByIdResponse)
  }

  // @@protoc_insertion_point(class_scope:game_engine.commission.v1.GetCommissionClaimByIdResponse)
  private static final com.game_engine.commission.v1.GetCommissionClaimByIdResponse DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.game_engine.commission.v1.GetCommissionClaimByIdResponse();
  }

  public static com.game_engine.commission.v1.GetCommissionClaimByIdResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<GetCommissionClaimByIdResponse>
      PARSER = new com.google.protobuf.AbstractParser<GetCommissionClaimByIdResponse>() {
    @java.lang.Override
    public GetCommissionClaimByIdResponse parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<GetCommissionClaimByIdResponse> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<GetCommissionClaimByIdResponse> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.game_engine.commission.v1.GetCommissionClaimByIdResponse getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

