// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: commission/v1/commission_service.proto

// Protobuf Java Version: 3.25.3
package com.game_engine.commission.v1;

public interface GetClaimsByStatusRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:game_engine.commission.v1.GetClaimsByStatusRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string user_id = 1 [json_name = "userId"];</code>
   * @return The userId.
   */
  java.lang.String getUserId();
  /**
   * <code>string user_id = 1 [json_name = "userId"];</code>
   * @return The bytes for userId.
   */
  com.google.protobuf.ByteString
      getUserIdBytes();

  /**
   * <code>string status = 2 [json_name = "status"];</code>
   * @return The status.
   */
  java.lang.String getStatus();
  /**
   * <code>string status = 2 [json_name = "status"];</code>
   * @return The bytes for status.
   */
  com.google.protobuf.ByteString
      getStatusBytes();

  /**
   * <code>int32 page = 3 [json_name = "page"];</code>
   * @return The page.
   */
  int getPage();

  /**
   * <code>int32 limit = 4 [json_name = "limit"];</code>
   * @return The limit.
   */
  int getLimit();
}
