// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: commission/v1/commission_service.proto

// Protobuf Java Version: 3.25.3
package com.game_engine.commission.v1;

public interface GetCommissionHistoryRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:game_engine.commission.v1.GetCommissionHistoryRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string agent_id = 1 [json_name = "agentId"];</code>
   * @return The agentId.
   */
  java.lang.String getAgentId();
  /**
   * <code>string agent_id = 1 [json_name = "agentId"];</code>
   * @return The bytes for agentId.
   */
  com.google.protobuf.ByteString
      getAgentIdBytes();

  /**
   * <code>string page = 2 [json_name = "page"];</code>
   * @return The page.
   */
  java.lang.String getPage();
  /**
   * <code>string page = 2 [json_name = "page"];</code>
   * @return The bytes for page.
   */
  com.google.protobuf.ByteString
      getPageBytes();

  /**
   * <code>string limit = 3 [json_name = "limit"];</code>
   * @return The limit.
   */
  java.lang.String getLimit();
  /**
   * <code>string limit = 3 [json_name = "limit"];</code>
   * @return The bytes for limit.
   */
  com.google.protobuf.ByteString
      getLimitBytes();
}
