// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: commission/v1/commission_service.proto

// Protobuf Java Version: 3.25.3
package com.game_engine.commission.v1;

/**
 * Protobuf type {@code game_engine.commission.v1.GetCommissionsByPeriodResponse}
 */
public final class GetCommissionsByPeriodResponse extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:game_engine.commission.v1.GetCommissionsByPeriodResponse)
    GetCommissionsByPeriodResponseOrBuilder {
private static final long serialVersionUID = 0L;
  // Use GetCommissionsByPeriodResponse.newBuilder() to construct.
  private GetCommissionsByPeriodResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private GetCommissionsByPeriodResponse() {
    commissions_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new GetCommissionsByPeriodResponse();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.game_engine.commission.v1.CommissionServiceOuterClass.internal_static_game_engine_commission_v1_GetCommissionsByPeriodResponse_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.game_engine.commission.v1.CommissionServiceOuterClass.internal_static_game_engine_commission_v1_GetCommissionsByPeriodResponse_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.game_engine.commission.v1.GetCommissionsByPeriodResponse.class, com.game_engine.commission.v1.GetCommissionsByPeriodResponse.Builder.class);
  }

  public static final int COMMISSIONS_FIELD_NUMBER = 1;
  @SuppressWarnings("serial")
  private java.util.List<com.game_engine.commission.v1.Commission> commissions_;
  /**
   * <code>repeated .game_engine.commission.v1.Commission commissions = 1 [json_name = "commissions"];</code>
   */
  @java.lang.Override
  public java.util.List<com.game_engine.commission.v1.Commission> getCommissionsList() {
    return commissions_;
  }
  /**
   * <code>repeated .game_engine.commission.v1.Commission commissions = 1 [json_name = "commissions"];</code>
   */
  @java.lang.Override
  public java.util.List<? extends com.game_engine.commission.v1.CommissionOrBuilder> 
      getCommissionsOrBuilderList() {
    return commissions_;
  }
  /**
   * <code>repeated .game_engine.commission.v1.Commission commissions = 1 [json_name = "commissions"];</code>
   */
  @java.lang.Override
  public int getCommissionsCount() {
    return commissions_.size();
  }
  /**
   * <code>repeated .game_engine.commission.v1.Commission commissions = 1 [json_name = "commissions"];</code>
   */
  @java.lang.Override
  public com.game_engine.commission.v1.Commission getCommissions(int index) {
    return commissions_.get(index);
  }
  /**
   * <code>repeated .game_engine.commission.v1.Commission commissions = 1 [json_name = "commissions"];</code>
   */
  @java.lang.Override
  public com.game_engine.commission.v1.CommissionOrBuilder getCommissionsOrBuilder(
      int index) {
    return commissions_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    for (int i = 0; i < commissions_.size(); i++) {
      output.writeMessage(1, commissions_.get(i));
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    for (int i = 0; i < commissions_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, commissions_.get(i));
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.game_engine.commission.v1.GetCommissionsByPeriodResponse)) {
      return super.equals(obj);
    }
    com.game_engine.commission.v1.GetCommissionsByPeriodResponse other = (com.game_engine.commission.v1.GetCommissionsByPeriodResponse) obj;

    if (!getCommissionsList()
        .equals(other.getCommissionsList())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (getCommissionsCount() > 0) {
      hash = (37 * hash) + COMMISSIONS_FIELD_NUMBER;
      hash = (53 * hash) + getCommissionsList().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.game_engine.commission.v1.GetCommissionsByPeriodResponse parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.game_engine.commission.v1.GetCommissionsByPeriodResponse parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.game_engine.commission.v1.GetCommissionsByPeriodResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.game_engine.commission.v1.GetCommissionsByPeriodResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.game_engine.commission.v1.GetCommissionsByPeriodResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.game_engine.commission.v1.GetCommissionsByPeriodResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.game_engine.commission.v1.GetCommissionsByPeriodResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.game_engine.commission.v1.GetCommissionsByPeriodResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static com.game_engine.commission.v1.GetCommissionsByPeriodResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static com.game_engine.commission.v1.GetCommissionsByPeriodResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.game_engine.commission.v1.GetCommissionsByPeriodResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.game_engine.commission.v1.GetCommissionsByPeriodResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.game_engine.commission.v1.GetCommissionsByPeriodResponse prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code game_engine.commission.v1.GetCommissionsByPeriodResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:game_engine.commission.v1.GetCommissionsByPeriodResponse)
      com.game_engine.commission.v1.GetCommissionsByPeriodResponseOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.game_engine.commission.v1.CommissionServiceOuterClass.internal_static_game_engine_commission_v1_GetCommissionsByPeriodResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.game_engine.commission.v1.CommissionServiceOuterClass.internal_static_game_engine_commission_v1_GetCommissionsByPeriodResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.game_engine.commission.v1.GetCommissionsByPeriodResponse.class, com.game_engine.commission.v1.GetCommissionsByPeriodResponse.Builder.class);
    }

    // Construct using com.game_engine.commission.v1.GetCommissionsByPeriodResponse.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      if (commissionsBuilder_ == null) {
        commissions_ = java.util.Collections.emptyList();
      } else {
        commissions_ = null;
        commissionsBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000001);
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.game_engine.commission.v1.CommissionServiceOuterClass.internal_static_game_engine_commission_v1_GetCommissionsByPeriodResponse_descriptor;
    }

    @java.lang.Override
    public com.game_engine.commission.v1.GetCommissionsByPeriodResponse getDefaultInstanceForType() {
      return com.game_engine.commission.v1.GetCommissionsByPeriodResponse.getDefaultInstance();
    }

    @java.lang.Override
    public com.game_engine.commission.v1.GetCommissionsByPeriodResponse build() {
      com.game_engine.commission.v1.GetCommissionsByPeriodResponse result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.game_engine.commission.v1.GetCommissionsByPeriodResponse buildPartial() {
      com.game_engine.commission.v1.GetCommissionsByPeriodResponse result = new com.game_engine.commission.v1.GetCommissionsByPeriodResponse(this);
      buildPartialRepeatedFields(result);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartialRepeatedFields(com.game_engine.commission.v1.GetCommissionsByPeriodResponse result) {
      if (commissionsBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0)) {
          commissions_ = java.util.Collections.unmodifiableList(commissions_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.commissions_ = commissions_;
      } else {
        result.commissions_ = commissionsBuilder_.build();
      }
    }

    private void buildPartial0(com.game_engine.commission.v1.GetCommissionsByPeriodResponse result) {
      int from_bitField0_ = bitField0_;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.game_engine.commission.v1.GetCommissionsByPeriodResponse) {
        return mergeFrom((com.game_engine.commission.v1.GetCommissionsByPeriodResponse)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.game_engine.commission.v1.GetCommissionsByPeriodResponse other) {
      if (other == com.game_engine.commission.v1.GetCommissionsByPeriodResponse.getDefaultInstance()) return this;
      if (commissionsBuilder_ == null) {
        if (!other.commissions_.isEmpty()) {
          if (commissions_.isEmpty()) {
            commissions_ = other.commissions_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureCommissionsIsMutable();
            commissions_.addAll(other.commissions_);
          }
          onChanged();
        }
      } else {
        if (!other.commissions_.isEmpty()) {
          if (commissionsBuilder_.isEmpty()) {
            commissionsBuilder_.dispose();
            commissionsBuilder_ = null;
            commissions_ = other.commissions_;
            bitField0_ = (bitField0_ & ~0x00000001);
            commissionsBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getCommissionsFieldBuilder() : null;
          } else {
            commissionsBuilder_.addAllMessages(other.commissions_);
          }
        }
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              com.game_engine.commission.v1.Commission m =
                  input.readMessage(
                      com.game_engine.commission.v1.Commission.parser(),
                      extensionRegistry);
              if (commissionsBuilder_ == null) {
                ensureCommissionsIsMutable();
                commissions_.add(m);
              } else {
                commissionsBuilder_.addMessage(m);
              }
              break;
            } // case 10
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private java.util.List<com.game_engine.commission.v1.Commission> commissions_ =
      java.util.Collections.emptyList();
    private void ensureCommissionsIsMutable() {
      if (!((bitField0_ & 0x00000001) != 0)) {
        commissions_ = new java.util.ArrayList<com.game_engine.commission.v1.Commission>(commissions_);
        bitField0_ |= 0x00000001;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.game_engine.commission.v1.Commission, com.game_engine.commission.v1.Commission.Builder, com.game_engine.commission.v1.CommissionOrBuilder> commissionsBuilder_;

    /**
     * <code>repeated .game_engine.commission.v1.Commission commissions = 1 [json_name = "commissions"];</code>
     */
    public java.util.List<com.game_engine.commission.v1.Commission> getCommissionsList() {
      if (commissionsBuilder_ == null) {
        return java.util.Collections.unmodifiableList(commissions_);
      } else {
        return commissionsBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .game_engine.commission.v1.Commission commissions = 1 [json_name = "commissions"];</code>
     */
    public int getCommissionsCount() {
      if (commissionsBuilder_ == null) {
        return commissions_.size();
      } else {
        return commissionsBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .game_engine.commission.v1.Commission commissions = 1 [json_name = "commissions"];</code>
     */
    public com.game_engine.commission.v1.Commission getCommissions(int index) {
      if (commissionsBuilder_ == null) {
        return commissions_.get(index);
      } else {
        return commissionsBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .game_engine.commission.v1.Commission commissions = 1 [json_name = "commissions"];</code>
     */
    public Builder setCommissions(
        int index, com.game_engine.commission.v1.Commission value) {
      if (commissionsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureCommissionsIsMutable();
        commissions_.set(index, value);
        onChanged();
      } else {
        commissionsBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .game_engine.commission.v1.Commission commissions = 1 [json_name = "commissions"];</code>
     */
    public Builder setCommissions(
        int index, com.game_engine.commission.v1.Commission.Builder builderForValue) {
      if (commissionsBuilder_ == null) {
        ensureCommissionsIsMutable();
        commissions_.set(index, builderForValue.build());
        onChanged();
      } else {
        commissionsBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .game_engine.commission.v1.Commission commissions = 1 [json_name = "commissions"];</code>
     */
    public Builder addCommissions(com.game_engine.commission.v1.Commission value) {
      if (commissionsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureCommissionsIsMutable();
        commissions_.add(value);
        onChanged();
      } else {
        commissionsBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .game_engine.commission.v1.Commission commissions = 1 [json_name = "commissions"];</code>
     */
    public Builder addCommissions(
        int index, com.game_engine.commission.v1.Commission value) {
      if (commissionsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureCommissionsIsMutable();
        commissions_.add(index, value);
        onChanged();
      } else {
        commissionsBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .game_engine.commission.v1.Commission commissions = 1 [json_name = "commissions"];</code>
     */
    public Builder addCommissions(
        com.game_engine.commission.v1.Commission.Builder builderForValue) {
      if (commissionsBuilder_ == null) {
        ensureCommissionsIsMutable();
        commissions_.add(builderForValue.build());
        onChanged();
      } else {
        commissionsBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .game_engine.commission.v1.Commission commissions = 1 [json_name = "commissions"];</code>
     */
    public Builder addCommissions(
        int index, com.game_engine.commission.v1.Commission.Builder builderForValue) {
      if (commissionsBuilder_ == null) {
        ensureCommissionsIsMutable();
        commissions_.add(index, builderForValue.build());
        onChanged();
      } else {
        commissionsBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .game_engine.commission.v1.Commission commissions = 1 [json_name = "commissions"];</code>
     */
    public Builder addAllCommissions(
        java.lang.Iterable<? extends com.game_engine.commission.v1.Commission> values) {
      if (commissionsBuilder_ == null) {
        ensureCommissionsIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, commissions_);
        onChanged();
      } else {
        commissionsBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .game_engine.commission.v1.Commission commissions = 1 [json_name = "commissions"];</code>
     */
    public Builder clearCommissions() {
      if (commissionsBuilder_ == null) {
        commissions_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
      } else {
        commissionsBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .game_engine.commission.v1.Commission commissions = 1 [json_name = "commissions"];</code>
     */
    public Builder removeCommissions(int index) {
      if (commissionsBuilder_ == null) {
        ensureCommissionsIsMutable();
        commissions_.remove(index);
        onChanged();
      } else {
        commissionsBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .game_engine.commission.v1.Commission commissions = 1 [json_name = "commissions"];</code>
     */
    public com.game_engine.commission.v1.Commission.Builder getCommissionsBuilder(
        int index) {
      return getCommissionsFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .game_engine.commission.v1.Commission commissions = 1 [json_name = "commissions"];</code>
     */
    public com.game_engine.commission.v1.CommissionOrBuilder getCommissionsOrBuilder(
        int index) {
      if (commissionsBuilder_ == null) {
        return commissions_.get(index);  } else {
        return commissionsBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .game_engine.commission.v1.Commission commissions = 1 [json_name = "commissions"];</code>
     */
    public java.util.List<? extends com.game_engine.commission.v1.CommissionOrBuilder> 
         getCommissionsOrBuilderList() {
      if (commissionsBuilder_ != null) {
        return commissionsBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(commissions_);
      }
    }
    /**
     * <code>repeated .game_engine.commission.v1.Commission commissions = 1 [json_name = "commissions"];</code>
     */
    public com.game_engine.commission.v1.Commission.Builder addCommissionsBuilder() {
      return getCommissionsFieldBuilder().addBuilder(
          com.game_engine.commission.v1.Commission.getDefaultInstance());
    }
    /**
     * <code>repeated .game_engine.commission.v1.Commission commissions = 1 [json_name = "commissions"];</code>
     */
    public com.game_engine.commission.v1.Commission.Builder addCommissionsBuilder(
        int index) {
      return getCommissionsFieldBuilder().addBuilder(
          index, com.game_engine.commission.v1.Commission.getDefaultInstance());
    }
    /**
     * <code>repeated .game_engine.commission.v1.Commission commissions = 1 [json_name = "commissions"];</code>
     */
    public java.util.List<com.game_engine.commission.v1.Commission.Builder> 
         getCommissionsBuilderList() {
      return getCommissionsFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.game_engine.commission.v1.Commission, com.game_engine.commission.v1.Commission.Builder, com.game_engine.commission.v1.CommissionOrBuilder> 
        getCommissionsFieldBuilder() {
      if (commissionsBuilder_ == null) {
        commissionsBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            com.game_engine.commission.v1.Commission, com.game_engine.commission.v1.Commission.Builder, com.game_engine.commission.v1.CommissionOrBuilder>(
                commissions_,
                ((bitField0_ & 0x00000001) != 0),
                getParentForChildren(),
                isClean());
        commissions_ = null;
      }
      return commissionsBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:game_engine.commission.v1.GetCommissionsByPeriodResponse)
  }

  // @@protoc_insertion_point(class_scope:game_engine.commission.v1.GetCommissionsByPeriodResponse)
  private static final com.game_engine.commission.v1.GetCommissionsByPeriodResponse DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.game_engine.commission.v1.GetCommissionsByPeriodResponse();
  }

  public static com.game_engine.commission.v1.GetCommissionsByPeriodResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<GetCommissionsByPeriodResponse>
      PARSER = new com.google.protobuf.AbstractParser<GetCommissionsByPeriodResponse>() {
    @java.lang.Override
    public GetCommissionsByPeriodResponse parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<GetCommissionsByPeriodResponse> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<GetCommissionsByPeriodResponse> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.game_engine.commission.v1.GetCommissionsByPeriodResponse getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

