// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: commission/v1/commission_service.proto

// Protobuf Java Version: 3.25.3
package com.game_engine.commission.v1;

/**
 * Protobuf type {@code game_engine.commission.v1.RebetClaimMsg}
 */
public final class RebetClaimMsg extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:game_engine.commission.v1.RebetClaimMsg)
    RebetClaimMsgOrBuilder {
private static final long serialVersionUID = 0L;
  // Use RebetClaimMsg.newBuilder() to construct.
  private RebetClaimMsg(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private RebetClaimMsg() {
    bonusCode_ = "";
    status_ = "";
    transactionId_ = "";
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new RebetClaimMsg();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.game_engine.commission.v1.CommissionServiceOuterClass.internal_static_game_engine_commission_v1_RebetClaimMsg_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.game_engine.commission.v1.CommissionServiceOuterClass.internal_static_game_engine_commission_v1_RebetClaimMsg_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.game_engine.commission.v1.RebetClaimMsg.class, com.game_engine.commission.v1.RebetClaimMsg.Builder.class);
  }

  private int bitField0_;
  public static final int ID_FIELD_NUMBER = 1;
  private long id_ = 0L;
  /**
   * <code>int64 id = 1 [json_name = "id"];</code>
   * @return The id.
   */
  @java.lang.Override
  public long getId() {
    return id_;
  }

  public static final int USER_ID_FIELD_NUMBER = 2;
  private long userId_ = 0L;
  /**
   * <code>int64 user_id = 2 [json_name = "userId"];</code>
   * @return The userId.
   */
  @java.lang.Override
  public long getUserId() {
    return userId_;
  }

  public static final int BONUS_ID_FIELD_NUMBER = 3;
  private long bonusId_ = 0L;
  /**
   * <code>int64 bonus_id = 3 [json_name = "bonusId"];</code>
   * @return The bonusId.
   */
  @java.lang.Override
  public long getBonusId() {
    return bonusId_;
  }

  public static final int BONUS_CODE_FIELD_NUMBER = 4;
  @SuppressWarnings("serial")
  private volatile java.lang.Object bonusCode_ = "";
  /**
   * <code>string bonus_code = 4 [json_name = "bonusCode"];</code>
   * @return The bonusCode.
   */
  @java.lang.Override
  public java.lang.String getBonusCode() {
    java.lang.Object ref = bonusCode_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      bonusCode_ = s;
      return s;
    }
  }
  /**
   * <code>string bonus_code = 4 [json_name = "bonusCode"];</code>
   * @return The bytes for bonusCode.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getBonusCodeBytes() {
    java.lang.Object ref = bonusCode_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      bonusCode_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int GAME_ID_FIELD_NUMBER = 5;
  private long gameId_ = 0L;
  /**
   * <code>int64 game_id = 5 [json_name = "gameId"];</code>
   * @return The gameId.
   */
  @java.lang.Override
  public long getGameId() {
    return gameId_;
  }

  public static final int BET_ID_FIELD_NUMBER = 6;
  private long betId_ = 0L;
  /**
   * <code>int64 bet_id = 6 [json_name = "betId"];</code>
   * @return The betId.
   */
  @java.lang.Override
  public long getBetId() {
    return betId_;
  }

  public static final int ORIGINAL_BONUS_AMOUNT_FIELD_NUMBER = 7;
  private double originalBonusAmount_ = 0D;
  /**
   * <code>double original_bonus_amount = 7 [json_name = "originalBonusAmount"];</code>
   * @return The originalBonusAmount.
   */
  @java.lang.Override
  public double getOriginalBonusAmount() {
    return originalBonusAmount_;
  }

  public static final int REBET_REQUIREMENT_FIELD_NUMBER = 8;
  private double rebetRequirement_ = 0D;
  /**
   * <code>double rebet_requirement = 8 [json_name = "rebetRequirement"];</code>
   * @return The rebetRequirement.
   */
  @java.lang.Override
  public double getRebetRequirement() {
    return rebetRequirement_;
  }

  public static final int CURRENT_REBET_AMOUNT_FIELD_NUMBER = 9;
  private double currentRebetAmount_ = 0D;
  /**
   * <code>double current_rebet_amount = 9 [json_name = "currentRebetAmount"];</code>
   * @return The currentRebetAmount.
   */
  @java.lang.Override
  public double getCurrentRebetAmount() {
    return currentRebetAmount_;
  }

  public static final int CLAIM_AMOUNT_FIELD_NUMBER = 10;
  private double claimAmount_ = 0D;
  /**
   * <code>double claim_amount = 10 [json_name = "claimAmount"];</code>
   * @return The claimAmount.
   */
  @java.lang.Override
  public double getClaimAmount() {
    return claimAmount_;
  }

  public static final int STATUS_FIELD_NUMBER = 11;
  @SuppressWarnings("serial")
  private volatile java.lang.Object status_ = "";
  /**
   * <pre>
   * ACTIVE, COMPLETED, CLAIMED, EXPIRED
   * </pre>
   *
   * <code>string status = 11 [json_name = "status"];</code>
   * @return The status.
   */
  @java.lang.Override
  public java.lang.String getStatus() {
    java.lang.Object ref = status_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      status_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * ACTIVE, COMPLETED, CLAIMED, EXPIRED
   * </pre>
   *
   * <code>string status = 11 [json_name = "status"];</code>
   * @return The bytes for status.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getStatusBytes() {
    java.lang.Object ref = status_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      status_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int EXPIRES_AT_FIELD_NUMBER = 12;
  private com.google.protobuf.Timestamp expiresAt_;
  /**
   * <code>.google.protobuf.Timestamp expires_at = 12 [json_name = "expiresAt"];</code>
   * @return Whether the expiresAt field is set.
   */
  @java.lang.Override
  public boolean hasExpiresAt() {
    return ((bitField0_ & 0x00000001) != 0);
  }
  /**
   * <code>.google.protobuf.Timestamp expires_at = 12 [json_name = "expiresAt"];</code>
   * @return The expiresAt.
   */
  @java.lang.Override
  public com.google.protobuf.Timestamp getExpiresAt() {
    return expiresAt_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : expiresAt_;
  }
  /**
   * <code>.google.protobuf.Timestamp expires_at = 12 [json_name = "expiresAt"];</code>
   */
  @java.lang.Override
  public com.google.protobuf.TimestampOrBuilder getExpiresAtOrBuilder() {
    return expiresAt_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : expiresAt_;
  }

  public static final int CLAIMED_AT_FIELD_NUMBER = 13;
  private com.google.protobuf.Timestamp claimedAt_;
  /**
   * <code>.google.protobuf.Timestamp claimed_at = 13 [json_name = "claimedAt"];</code>
   * @return Whether the claimedAt field is set.
   */
  @java.lang.Override
  public boolean hasClaimedAt() {
    return ((bitField0_ & 0x00000002) != 0);
  }
  /**
   * <code>.google.protobuf.Timestamp claimed_at = 13 [json_name = "claimedAt"];</code>
   * @return The claimedAt.
   */
  @java.lang.Override
  public com.google.protobuf.Timestamp getClaimedAt() {
    return claimedAt_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : claimedAt_;
  }
  /**
   * <code>.google.protobuf.Timestamp claimed_at = 13 [json_name = "claimedAt"];</code>
   */
  @java.lang.Override
  public com.google.protobuf.TimestampOrBuilder getClaimedAtOrBuilder() {
    return claimedAt_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : claimedAt_;
  }

  public static final int TRANSACTION_ID_FIELD_NUMBER = 14;
  @SuppressWarnings("serial")
  private volatile java.lang.Object transactionId_ = "";
  /**
   * <code>string transaction_id = 14 [json_name = "transactionId"];</code>
   * @return The transactionId.
   */
  @java.lang.Override
  public java.lang.String getTransactionId() {
    java.lang.Object ref = transactionId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      transactionId_ = s;
      return s;
    }
  }
  /**
   * <code>string transaction_id = 14 [json_name = "transactionId"];</code>
   * @return The bytes for transactionId.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getTransactionIdBytes() {
    java.lang.Object ref = transactionId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      transactionId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int CLAIMABLE_FIELD_NUMBER = 15;
  private boolean claimable_ = false;
  /**
   * <code>bool claimable = 15 [json_name = "claimable"];</code>
   * @return The claimable.
   */
  @java.lang.Override
  public boolean getClaimable() {
    return claimable_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (id_ != 0L) {
      output.writeInt64(1, id_);
    }
    if (userId_ != 0L) {
      output.writeInt64(2, userId_);
    }
    if (bonusId_ != 0L) {
      output.writeInt64(3, bonusId_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(bonusCode_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 4, bonusCode_);
    }
    if (gameId_ != 0L) {
      output.writeInt64(5, gameId_);
    }
    if (betId_ != 0L) {
      output.writeInt64(6, betId_);
    }
    if (java.lang.Double.doubleToRawLongBits(originalBonusAmount_) != 0) {
      output.writeDouble(7, originalBonusAmount_);
    }
    if (java.lang.Double.doubleToRawLongBits(rebetRequirement_) != 0) {
      output.writeDouble(8, rebetRequirement_);
    }
    if (java.lang.Double.doubleToRawLongBits(currentRebetAmount_) != 0) {
      output.writeDouble(9, currentRebetAmount_);
    }
    if (java.lang.Double.doubleToRawLongBits(claimAmount_) != 0) {
      output.writeDouble(10, claimAmount_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(status_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 11, status_);
    }
    if (((bitField0_ & 0x00000001) != 0)) {
      output.writeMessage(12, getExpiresAt());
    }
    if (((bitField0_ & 0x00000002) != 0)) {
      output.writeMessage(13, getClaimedAt());
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(transactionId_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 14, transactionId_);
    }
    if (claimable_ != false) {
      output.writeBool(15, claimable_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (id_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(1, id_);
    }
    if (userId_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(2, userId_);
    }
    if (bonusId_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(3, bonusId_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(bonusCode_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, bonusCode_);
    }
    if (gameId_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(5, gameId_);
    }
    if (betId_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(6, betId_);
    }
    if (java.lang.Double.doubleToRawLongBits(originalBonusAmount_) != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeDoubleSize(7, originalBonusAmount_);
    }
    if (java.lang.Double.doubleToRawLongBits(rebetRequirement_) != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeDoubleSize(8, rebetRequirement_);
    }
    if (java.lang.Double.doubleToRawLongBits(currentRebetAmount_) != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeDoubleSize(9, currentRebetAmount_);
    }
    if (java.lang.Double.doubleToRawLongBits(claimAmount_) != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeDoubleSize(10, claimAmount_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(status_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(11, status_);
    }
    if (((bitField0_ & 0x00000001) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(12, getExpiresAt());
    }
    if (((bitField0_ & 0x00000002) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(13, getClaimedAt());
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(transactionId_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(14, transactionId_);
    }
    if (claimable_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(15, claimable_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.game_engine.commission.v1.RebetClaimMsg)) {
      return super.equals(obj);
    }
    com.game_engine.commission.v1.RebetClaimMsg other = (com.game_engine.commission.v1.RebetClaimMsg) obj;

    if (getId()
        != other.getId()) return false;
    if (getUserId()
        != other.getUserId()) return false;
    if (getBonusId()
        != other.getBonusId()) return false;
    if (!getBonusCode()
        .equals(other.getBonusCode())) return false;
    if (getGameId()
        != other.getGameId()) return false;
    if (getBetId()
        != other.getBetId()) return false;
    if (java.lang.Double.doubleToLongBits(getOriginalBonusAmount())
        != java.lang.Double.doubleToLongBits(
            other.getOriginalBonusAmount())) return false;
    if (java.lang.Double.doubleToLongBits(getRebetRequirement())
        != java.lang.Double.doubleToLongBits(
            other.getRebetRequirement())) return false;
    if (java.lang.Double.doubleToLongBits(getCurrentRebetAmount())
        != java.lang.Double.doubleToLongBits(
            other.getCurrentRebetAmount())) return false;
    if (java.lang.Double.doubleToLongBits(getClaimAmount())
        != java.lang.Double.doubleToLongBits(
            other.getClaimAmount())) return false;
    if (!getStatus()
        .equals(other.getStatus())) return false;
    if (hasExpiresAt() != other.hasExpiresAt()) return false;
    if (hasExpiresAt()) {
      if (!getExpiresAt()
          .equals(other.getExpiresAt())) return false;
    }
    if (hasClaimedAt() != other.hasClaimedAt()) return false;
    if (hasClaimedAt()) {
      if (!getClaimedAt()
          .equals(other.getClaimedAt())) return false;
    }
    if (!getTransactionId()
        .equals(other.getTransactionId())) return false;
    if (getClaimable()
        != other.getClaimable()) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + ID_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getId());
    hash = (37 * hash) + USER_ID_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getUserId());
    hash = (37 * hash) + BONUS_ID_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getBonusId());
    hash = (37 * hash) + BONUS_CODE_FIELD_NUMBER;
    hash = (53 * hash) + getBonusCode().hashCode();
    hash = (37 * hash) + GAME_ID_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getGameId());
    hash = (37 * hash) + BET_ID_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getBetId());
    hash = (37 * hash) + ORIGINAL_BONUS_AMOUNT_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        java.lang.Double.doubleToLongBits(getOriginalBonusAmount()));
    hash = (37 * hash) + REBET_REQUIREMENT_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        java.lang.Double.doubleToLongBits(getRebetRequirement()));
    hash = (37 * hash) + CURRENT_REBET_AMOUNT_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        java.lang.Double.doubleToLongBits(getCurrentRebetAmount()));
    hash = (37 * hash) + CLAIM_AMOUNT_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        java.lang.Double.doubleToLongBits(getClaimAmount()));
    hash = (37 * hash) + STATUS_FIELD_NUMBER;
    hash = (53 * hash) + getStatus().hashCode();
    if (hasExpiresAt()) {
      hash = (37 * hash) + EXPIRES_AT_FIELD_NUMBER;
      hash = (53 * hash) + getExpiresAt().hashCode();
    }
    if (hasClaimedAt()) {
      hash = (37 * hash) + CLAIMED_AT_FIELD_NUMBER;
      hash = (53 * hash) + getClaimedAt().hashCode();
    }
    hash = (37 * hash) + TRANSACTION_ID_FIELD_NUMBER;
    hash = (53 * hash) + getTransactionId().hashCode();
    hash = (37 * hash) + CLAIMABLE_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
        getClaimable());
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.game_engine.commission.v1.RebetClaimMsg parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.game_engine.commission.v1.RebetClaimMsg parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.game_engine.commission.v1.RebetClaimMsg parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.game_engine.commission.v1.RebetClaimMsg parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.game_engine.commission.v1.RebetClaimMsg parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.game_engine.commission.v1.RebetClaimMsg parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.game_engine.commission.v1.RebetClaimMsg parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.game_engine.commission.v1.RebetClaimMsg parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static com.game_engine.commission.v1.RebetClaimMsg parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static com.game_engine.commission.v1.RebetClaimMsg parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.game_engine.commission.v1.RebetClaimMsg parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.game_engine.commission.v1.RebetClaimMsg parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.game_engine.commission.v1.RebetClaimMsg prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code game_engine.commission.v1.RebetClaimMsg}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:game_engine.commission.v1.RebetClaimMsg)
      com.game_engine.commission.v1.RebetClaimMsgOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.game_engine.commission.v1.CommissionServiceOuterClass.internal_static_game_engine_commission_v1_RebetClaimMsg_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.game_engine.commission.v1.CommissionServiceOuterClass.internal_static_game_engine_commission_v1_RebetClaimMsg_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.game_engine.commission.v1.RebetClaimMsg.class, com.game_engine.commission.v1.RebetClaimMsg.Builder.class);
    }

    // Construct using com.game_engine.commission.v1.RebetClaimMsg.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getExpiresAtFieldBuilder();
        getClaimedAtFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      id_ = 0L;
      userId_ = 0L;
      bonusId_ = 0L;
      bonusCode_ = "";
      gameId_ = 0L;
      betId_ = 0L;
      originalBonusAmount_ = 0D;
      rebetRequirement_ = 0D;
      currentRebetAmount_ = 0D;
      claimAmount_ = 0D;
      status_ = "";
      expiresAt_ = null;
      if (expiresAtBuilder_ != null) {
        expiresAtBuilder_.dispose();
        expiresAtBuilder_ = null;
      }
      claimedAt_ = null;
      if (claimedAtBuilder_ != null) {
        claimedAtBuilder_.dispose();
        claimedAtBuilder_ = null;
      }
      transactionId_ = "";
      claimable_ = false;
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.game_engine.commission.v1.CommissionServiceOuterClass.internal_static_game_engine_commission_v1_RebetClaimMsg_descriptor;
    }

    @java.lang.Override
    public com.game_engine.commission.v1.RebetClaimMsg getDefaultInstanceForType() {
      return com.game_engine.commission.v1.RebetClaimMsg.getDefaultInstance();
    }

    @java.lang.Override
    public com.game_engine.commission.v1.RebetClaimMsg build() {
      com.game_engine.commission.v1.RebetClaimMsg result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.game_engine.commission.v1.RebetClaimMsg buildPartial() {
      com.game_engine.commission.v1.RebetClaimMsg result = new com.game_engine.commission.v1.RebetClaimMsg(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(com.game_engine.commission.v1.RebetClaimMsg result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.id_ = id_;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.userId_ = userId_;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.bonusId_ = bonusId_;
      }
      if (((from_bitField0_ & 0x00000008) != 0)) {
        result.bonusCode_ = bonusCode_;
      }
      if (((from_bitField0_ & 0x00000010) != 0)) {
        result.gameId_ = gameId_;
      }
      if (((from_bitField0_ & 0x00000020) != 0)) {
        result.betId_ = betId_;
      }
      if (((from_bitField0_ & 0x00000040) != 0)) {
        result.originalBonusAmount_ = originalBonusAmount_;
      }
      if (((from_bitField0_ & 0x00000080) != 0)) {
        result.rebetRequirement_ = rebetRequirement_;
      }
      if (((from_bitField0_ & 0x00000100) != 0)) {
        result.currentRebetAmount_ = currentRebetAmount_;
      }
      if (((from_bitField0_ & 0x00000200) != 0)) {
        result.claimAmount_ = claimAmount_;
      }
      if (((from_bitField0_ & 0x00000400) != 0)) {
        result.status_ = status_;
      }
      int to_bitField0_ = 0;
      if (((from_bitField0_ & 0x00000800) != 0)) {
        result.expiresAt_ = expiresAtBuilder_ == null
            ? expiresAt_
            : expiresAtBuilder_.build();
        to_bitField0_ |= 0x00000001;
      }
      if (((from_bitField0_ & 0x00001000) != 0)) {
        result.claimedAt_ = claimedAtBuilder_ == null
            ? claimedAt_
            : claimedAtBuilder_.build();
        to_bitField0_ |= 0x00000002;
      }
      if (((from_bitField0_ & 0x00002000) != 0)) {
        result.transactionId_ = transactionId_;
      }
      if (((from_bitField0_ & 0x00004000) != 0)) {
        result.claimable_ = claimable_;
      }
      result.bitField0_ |= to_bitField0_;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.game_engine.commission.v1.RebetClaimMsg) {
        return mergeFrom((com.game_engine.commission.v1.RebetClaimMsg)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.game_engine.commission.v1.RebetClaimMsg other) {
      if (other == com.game_engine.commission.v1.RebetClaimMsg.getDefaultInstance()) return this;
      if (other.getId() != 0L) {
        setId(other.getId());
      }
      if (other.getUserId() != 0L) {
        setUserId(other.getUserId());
      }
      if (other.getBonusId() != 0L) {
        setBonusId(other.getBonusId());
      }
      if (!other.getBonusCode().isEmpty()) {
        bonusCode_ = other.bonusCode_;
        bitField0_ |= 0x00000008;
        onChanged();
      }
      if (other.getGameId() != 0L) {
        setGameId(other.getGameId());
      }
      if (other.getBetId() != 0L) {
        setBetId(other.getBetId());
      }
      if (other.getOriginalBonusAmount() != 0D) {
        setOriginalBonusAmount(other.getOriginalBonusAmount());
      }
      if (other.getRebetRequirement() != 0D) {
        setRebetRequirement(other.getRebetRequirement());
      }
      if (other.getCurrentRebetAmount() != 0D) {
        setCurrentRebetAmount(other.getCurrentRebetAmount());
      }
      if (other.getClaimAmount() != 0D) {
        setClaimAmount(other.getClaimAmount());
      }
      if (!other.getStatus().isEmpty()) {
        status_ = other.status_;
        bitField0_ |= 0x00000400;
        onChanged();
      }
      if (other.hasExpiresAt()) {
        mergeExpiresAt(other.getExpiresAt());
      }
      if (other.hasClaimedAt()) {
        mergeClaimedAt(other.getClaimedAt());
      }
      if (!other.getTransactionId().isEmpty()) {
        transactionId_ = other.transactionId_;
        bitField0_ |= 0x00002000;
        onChanged();
      }
      if (other.getClaimable() != false) {
        setClaimable(other.getClaimable());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              id_ = input.readInt64();
              bitField0_ |= 0x00000001;
              break;
            } // case 8
            case 16: {
              userId_ = input.readInt64();
              bitField0_ |= 0x00000002;
              break;
            } // case 16
            case 24: {
              bonusId_ = input.readInt64();
              bitField0_ |= 0x00000004;
              break;
            } // case 24
            case 34: {
              bonusCode_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000008;
              break;
            } // case 34
            case 40: {
              gameId_ = input.readInt64();
              bitField0_ |= 0x00000010;
              break;
            } // case 40
            case 48: {
              betId_ = input.readInt64();
              bitField0_ |= 0x00000020;
              break;
            } // case 48
            case 57: {
              originalBonusAmount_ = input.readDouble();
              bitField0_ |= 0x00000040;
              break;
            } // case 57
            case 65: {
              rebetRequirement_ = input.readDouble();
              bitField0_ |= 0x00000080;
              break;
            } // case 65
            case 73: {
              currentRebetAmount_ = input.readDouble();
              bitField0_ |= 0x00000100;
              break;
            } // case 73
            case 81: {
              claimAmount_ = input.readDouble();
              bitField0_ |= 0x00000200;
              break;
            } // case 81
            case 90: {
              status_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000400;
              break;
            } // case 90
            case 98: {
              input.readMessage(
                  getExpiresAtFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000800;
              break;
            } // case 98
            case 106: {
              input.readMessage(
                  getClaimedAtFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00001000;
              break;
            } // case 106
            case 114: {
              transactionId_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00002000;
              break;
            } // case 114
            case 120: {
              claimable_ = input.readBool();
              bitField0_ |= 0x00004000;
              break;
            } // case 120
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private long id_ ;
    /**
     * <code>int64 id = 1 [json_name = "id"];</code>
     * @return The id.
     */
    @java.lang.Override
    public long getId() {
      return id_;
    }
    /**
     * <code>int64 id = 1 [json_name = "id"];</code>
     * @param value The id to set.
     * @return This builder for chaining.
     */
    public Builder setId(long value) {

      id_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>int64 id = 1 [json_name = "id"];</code>
     * @return This builder for chaining.
     */
    public Builder clearId() {
      bitField0_ = (bitField0_ & ~0x00000001);
      id_ = 0L;
      onChanged();
      return this;
    }

    private long userId_ ;
    /**
     * <code>int64 user_id = 2 [json_name = "userId"];</code>
     * @return The userId.
     */
    @java.lang.Override
    public long getUserId() {
      return userId_;
    }
    /**
     * <code>int64 user_id = 2 [json_name = "userId"];</code>
     * @param value The userId to set.
     * @return This builder for chaining.
     */
    public Builder setUserId(long value) {

      userId_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>int64 user_id = 2 [json_name = "userId"];</code>
     * @return This builder for chaining.
     */
    public Builder clearUserId() {
      bitField0_ = (bitField0_ & ~0x00000002);
      userId_ = 0L;
      onChanged();
      return this;
    }

    private long bonusId_ ;
    /**
     * <code>int64 bonus_id = 3 [json_name = "bonusId"];</code>
     * @return The bonusId.
     */
    @java.lang.Override
    public long getBonusId() {
      return bonusId_;
    }
    /**
     * <code>int64 bonus_id = 3 [json_name = "bonusId"];</code>
     * @param value The bonusId to set.
     * @return This builder for chaining.
     */
    public Builder setBonusId(long value) {

      bonusId_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <code>int64 bonus_id = 3 [json_name = "bonusId"];</code>
     * @return This builder for chaining.
     */
    public Builder clearBonusId() {
      bitField0_ = (bitField0_ & ~0x00000004);
      bonusId_ = 0L;
      onChanged();
      return this;
    }

    private java.lang.Object bonusCode_ = "";
    /**
     * <code>string bonus_code = 4 [json_name = "bonusCode"];</code>
     * @return The bonusCode.
     */
    public java.lang.String getBonusCode() {
      java.lang.Object ref = bonusCode_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        bonusCode_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string bonus_code = 4 [json_name = "bonusCode"];</code>
     * @return The bytes for bonusCode.
     */
    public com.google.protobuf.ByteString
        getBonusCodeBytes() {
      java.lang.Object ref = bonusCode_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        bonusCode_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string bonus_code = 4 [json_name = "bonusCode"];</code>
     * @param value The bonusCode to set.
     * @return This builder for chaining.
     */
    public Builder setBonusCode(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      bonusCode_ = value;
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <code>string bonus_code = 4 [json_name = "bonusCode"];</code>
     * @return This builder for chaining.
     */
    public Builder clearBonusCode() {
      bonusCode_ = getDefaultInstance().getBonusCode();
      bitField0_ = (bitField0_ & ~0x00000008);
      onChanged();
      return this;
    }
    /**
     * <code>string bonus_code = 4 [json_name = "bonusCode"];</code>
     * @param value The bytes for bonusCode to set.
     * @return This builder for chaining.
     */
    public Builder setBonusCodeBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      bonusCode_ = value;
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }

    private long gameId_ ;
    /**
     * <code>int64 game_id = 5 [json_name = "gameId"];</code>
     * @return The gameId.
     */
    @java.lang.Override
    public long getGameId() {
      return gameId_;
    }
    /**
     * <code>int64 game_id = 5 [json_name = "gameId"];</code>
     * @param value The gameId to set.
     * @return This builder for chaining.
     */
    public Builder setGameId(long value) {

      gameId_ = value;
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }
    /**
     * <code>int64 game_id = 5 [json_name = "gameId"];</code>
     * @return This builder for chaining.
     */
    public Builder clearGameId() {
      bitField0_ = (bitField0_ & ~0x00000010);
      gameId_ = 0L;
      onChanged();
      return this;
    }

    private long betId_ ;
    /**
     * <code>int64 bet_id = 6 [json_name = "betId"];</code>
     * @return The betId.
     */
    @java.lang.Override
    public long getBetId() {
      return betId_;
    }
    /**
     * <code>int64 bet_id = 6 [json_name = "betId"];</code>
     * @param value The betId to set.
     * @return This builder for chaining.
     */
    public Builder setBetId(long value) {

      betId_ = value;
      bitField0_ |= 0x00000020;
      onChanged();
      return this;
    }
    /**
     * <code>int64 bet_id = 6 [json_name = "betId"];</code>
     * @return This builder for chaining.
     */
    public Builder clearBetId() {
      bitField0_ = (bitField0_ & ~0x00000020);
      betId_ = 0L;
      onChanged();
      return this;
    }

    private double originalBonusAmount_ ;
    /**
     * <code>double original_bonus_amount = 7 [json_name = "originalBonusAmount"];</code>
     * @return The originalBonusAmount.
     */
    @java.lang.Override
    public double getOriginalBonusAmount() {
      return originalBonusAmount_;
    }
    /**
     * <code>double original_bonus_amount = 7 [json_name = "originalBonusAmount"];</code>
     * @param value The originalBonusAmount to set.
     * @return This builder for chaining.
     */
    public Builder setOriginalBonusAmount(double value) {

      originalBonusAmount_ = value;
      bitField0_ |= 0x00000040;
      onChanged();
      return this;
    }
    /**
     * <code>double original_bonus_amount = 7 [json_name = "originalBonusAmount"];</code>
     * @return This builder for chaining.
     */
    public Builder clearOriginalBonusAmount() {
      bitField0_ = (bitField0_ & ~0x00000040);
      originalBonusAmount_ = 0D;
      onChanged();
      return this;
    }

    private double rebetRequirement_ ;
    /**
     * <code>double rebet_requirement = 8 [json_name = "rebetRequirement"];</code>
     * @return The rebetRequirement.
     */
    @java.lang.Override
    public double getRebetRequirement() {
      return rebetRequirement_;
    }
    /**
     * <code>double rebet_requirement = 8 [json_name = "rebetRequirement"];</code>
     * @param value The rebetRequirement to set.
     * @return This builder for chaining.
     */
    public Builder setRebetRequirement(double value) {

      rebetRequirement_ = value;
      bitField0_ |= 0x00000080;
      onChanged();
      return this;
    }
    /**
     * <code>double rebet_requirement = 8 [json_name = "rebetRequirement"];</code>
     * @return This builder for chaining.
     */
    public Builder clearRebetRequirement() {
      bitField0_ = (bitField0_ & ~0x00000080);
      rebetRequirement_ = 0D;
      onChanged();
      return this;
    }

    private double currentRebetAmount_ ;
    /**
     * <code>double current_rebet_amount = 9 [json_name = "currentRebetAmount"];</code>
     * @return The currentRebetAmount.
     */
    @java.lang.Override
    public double getCurrentRebetAmount() {
      return currentRebetAmount_;
    }
    /**
     * <code>double current_rebet_amount = 9 [json_name = "currentRebetAmount"];</code>
     * @param value The currentRebetAmount to set.
     * @return This builder for chaining.
     */
    public Builder setCurrentRebetAmount(double value) {

      currentRebetAmount_ = value;
      bitField0_ |= 0x00000100;
      onChanged();
      return this;
    }
    /**
     * <code>double current_rebet_amount = 9 [json_name = "currentRebetAmount"];</code>
     * @return This builder for chaining.
     */
    public Builder clearCurrentRebetAmount() {
      bitField0_ = (bitField0_ & ~0x00000100);
      currentRebetAmount_ = 0D;
      onChanged();
      return this;
    }

    private double claimAmount_ ;
    /**
     * <code>double claim_amount = 10 [json_name = "claimAmount"];</code>
     * @return The claimAmount.
     */
    @java.lang.Override
    public double getClaimAmount() {
      return claimAmount_;
    }
    /**
     * <code>double claim_amount = 10 [json_name = "claimAmount"];</code>
     * @param value The claimAmount to set.
     * @return This builder for chaining.
     */
    public Builder setClaimAmount(double value) {

      claimAmount_ = value;
      bitField0_ |= 0x00000200;
      onChanged();
      return this;
    }
    /**
     * <code>double claim_amount = 10 [json_name = "claimAmount"];</code>
     * @return This builder for chaining.
     */
    public Builder clearClaimAmount() {
      bitField0_ = (bitField0_ & ~0x00000200);
      claimAmount_ = 0D;
      onChanged();
      return this;
    }

    private java.lang.Object status_ = "";
    /**
     * <pre>
     * ACTIVE, COMPLETED, CLAIMED, EXPIRED
     * </pre>
     *
     * <code>string status = 11 [json_name = "status"];</code>
     * @return The status.
     */
    public java.lang.String getStatus() {
      java.lang.Object ref = status_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        status_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * ACTIVE, COMPLETED, CLAIMED, EXPIRED
     * </pre>
     *
     * <code>string status = 11 [json_name = "status"];</code>
     * @return The bytes for status.
     */
    public com.google.protobuf.ByteString
        getStatusBytes() {
      java.lang.Object ref = status_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        status_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * ACTIVE, COMPLETED, CLAIMED, EXPIRED
     * </pre>
     *
     * <code>string status = 11 [json_name = "status"];</code>
     * @param value The status to set.
     * @return This builder for chaining.
     */
    public Builder setStatus(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      status_ = value;
      bitField0_ |= 0x00000400;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * ACTIVE, COMPLETED, CLAIMED, EXPIRED
     * </pre>
     *
     * <code>string status = 11 [json_name = "status"];</code>
     * @return This builder for chaining.
     */
    public Builder clearStatus() {
      status_ = getDefaultInstance().getStatus();
      bitField0_ = (bitField0_ & ~0x00000400);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * ACTIVE, COMPLETED, CLAIMED, EXPIRED
     * </pre>
     *
     * <code>string status = 11 [json_name = "status"];</code>
     * @param value The bytes for status to set.
     * @return This builder for chaining.
     */
    public Builder setStatusBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      status_ = value;
      bitField0_ |= 0x00000400;
      onChanged();
      return this;
    }

    private com.google.protobuf.Timestamp expiresAt_;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder> expiresAtBuilder_;
    /**
     * <code>.google.protobuf.Timestamp expires_at = 12 [json_name = "expiresAt"];</code>
     * @return Whether the expiresAt field is set.
     */
    public boolean hasExpiresAt() {
      return ((bitField0_ & 0x00000800) != 0);
    }
    /**
     * <code>.google.protobuf.Timestamp expires_at = 12 [json_name = "expiresAt"];</code>
     * @return The expiresAt.
     */
    public com.google.protobuf.Timestamp getExpiresAt() {
      if (expiresAtBuilder_ == null) {
        return expiresAt_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : expiresAt_;
      } else {
        return expiresAtBuilder_.getMessage();
      }
    }
    /**
     * <code>.google.protobuf.Timestamp expires_at = 12 [json_name = "expiresAt"];</code>
     */
    public Builder setExpiresAt(com.google.protobuf.Timestamp value) {
      if (expiresAtBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        expiresAt_ = value;
      } else {
        expiresAtBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000800;
      onChanged();
      return this;
    }
    /**
     * <code>.google.protobuf.Timestamp expires_at = 12 [json_name = "expiresAt"];</code>
     */
    public Builder setExpiresAt(
        com.google.protobuf.Timestamp.Builder builderForValue) {
      if (expiresAtBuilder_ == null) {
        expiresAt_ = builderForValue.build();
      } else {
        expiresAtBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000800;
      onChanged();
      return this;
    }
    /**
     * <code>.google.protobuf.Timestamp expires_at = 12 [json_name = "expiresAt"];</code>
     */
    public Builder mergeExpiresAt(com.google.protobuf.Timestamp value) {
      if (expiresAtBuilder_ == null) {
        if (((bitField0_ & 0x00000800) != 0) &&
          expiresAt_ != null &&
          expiresAt_ != com.google.protobuf.Timestamp.getDefaultInstance()) {
          getExpiresAtBuilder().mergeFrom(value);
        } else {
          expiresAt_ = value;
        }
      } else {
        expiresAtBuilder_.mergeFrom(value);
      }
      if (expiresAt_ != null) {
        bitField0_ |= 0x00000800;
        onChanged();
      }
      return this;
    }
    /**
     * <code>.google.protobuf.Timestamp expires_at = 12 [json_name = "expiresAt"];</code>
     */
    public Builder clearExpiresAt() {
      bitField0_ = (bitField0_ & ~0x00000800);
      expiresAt_ = null;
      if (expiresAtBuilder_ != null) {
        expiresAtBuilder_.dispose();
        expiresAtBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <code>.google.protobuf.Timestamp expires_at = 12 [json_name = "expiresAt"];</code>
     */
    public com.google.protobuf.Timestamp.Builder getExpiresAtBuilder() {
      bitField0_ |= 0x00000800;
      onChanged();
      return getExpiresAtFieldBuilder().getBuilder();
    }
    /**
     * <code>.google.protobuf.Timestamp expires_at = 12 [json_name = "expiresAt"];</code>
     */
    public com.google.protobuf.TimestampOrBuilder getExpiresAtOrBuilder() {
      if (expiresAtBuilder_ != null) {
        return expiresAtBuilder_.getMessageOrBuilder();
      } else {
        return expiresAt_ == null ?
            com.google.protobuf.Timestamp.getDefaultInstance() : expiresAt_;
      }
    }
    /**
     * <code>.google.protobuf.Timestamp expires_at = 12 [json_name = "expiresAt"];</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder> 
        getExpiresAtFieldBuilder() {
      if (expiresAtBuilder_ == null) {
        expiresAtBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder>(
                getExpiresAt(),
                getParentForChildren(),
                isClean());
        expiresAt_ = null;
      }
      return expiresAtBuilder_;
    }

    private com.google.protobuf.Timestamp claimedAt_;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder> claimedAtBuilder_;
    /**
     * <code>.google.protobuf.Timestamp claimed_at = 13 [json_name = "claimedAt"];</code>
     * @return Whether the claimedAt field is set.
     */
    public boolean hasClaimedAt() {
      return ((bitField0_ & 0x00001000) != 0);
    }
    /**
     * <code>.google.protobuf.Timestamp claimed_at = 13 [json_name = "claimedAt"];</code>
     * @return The claimedAt.
     */
    public com.google.protobuf.Timestamp getClaimedAt() {
      if (claimedAtBuilder_ == null) {
        return claimedAt_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : claimedAt_;
      } else {
        return claimedAtBuilder_.getMessage();
      }
    }
    /**
     * <code>.google.protobuf.Timestamp claimed_at = 13 [json_name = "claimedAt"];</code>
     */
    public Builder setClaimedAt(com.google.protobuf.Timestamp value) {
      if (claimedAtBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        claimedAt_ = value;
      } else {
        claimedAtBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00001000;
      onChanged();
      return this;
    }
    /**
     * <code>.google.protobuf.Timestamp claimed_at = 13 [json_name = "claimedAt"];</code>
     */
    public Builder setClaimedAt(
        com.google.protobuf.Timestamp.Builder builderForValue) {
      if (claimedAtBuilder_ == null) {
        claimedAt_ = builderForValue.build();
      } else {
        claimedAtBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00001000;
      onChanged();
      return this;
    }
    /**
     * <code>.google.protobuf.Timestamp claimed_at = 13 [json_name = "claimedAt"];</code>
     */
    public Builder mergeClaimedAt(com.google.protobuf.Timestamp value) {
      if (claimedAtBuilder_ == null) {
        if (((bitField0_ & 0x00001000) != 0) &&
          claimedAt_ != null &&
          claimedAt_ != com.google.protobuf.Timestamp.getDefaultInstance()) {
          getClaimedAtBuilder().mergeFrom(value);
        } else {
          claimedAt_ = value;
        }
      } else {
        claimedAtBuilder_.mergeFrom(value);
      }
      if (claimedAt_ != null) {
        bitField0_ |= 0x00001000;
        onChanged();
      }
      return this;
    }
    /**
     * <code>.google.protobuf.Timestamp claimed_at = 13 [json_name = "claimedAt"];</code>
     */
    public Builder clearClaimedAt() {
      bitField0_ = (bitField0_ & ~0x00001000);
      claimedAt_ = null;
      if (claimedAtBuilder_ != null) {
        claimedAtBuilder_.dispose();
        claimedAtBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <code>.google.protobuf.Timestamp claimed_at = 13 [json_name = "claimedAt"];</code>
     */
    public com.google.protobuf.Timestamp.Builder getClaimedAtBuilder() {
      bitField0_ |= 0x00001000;
      onChanged();
      return getClaimedAtFieldBuilder().getBuilder();
    }
    /**
     * <code>.google.protobuf.Timestamp claimed_at = 13 [json_name = "claimedAt"];</code>
     */
    public com.google.protobuf.TimestampOrBuilder getClaimedAtOrBuilder() {
      if (claimedAtBuilder_ != null) {
        return claimedAtBuilder_.getMessageOrBuilder();
      } else {
        return claimedAt_ == null ?
            com.google.protobuf.Timestamp.getDefaultInstance() : claimedAt_;
      }
    }
    /**
     * <code>.google.protobuf.Timestamp claimed_at = 13 [json_name = "claimedAt"];</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder> 
        getClaimedAtFieldBuilder() {
      if (claimedAtBuilder_ == null) {
        claimedAtBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder>(
                getClaimedAt(),
                getParentForChildren(),
                isClean());
        claimedAt_ = null;
      }
      return claimedAtBuilder_;
    }

    private java.lang.Object transactionId_ = "";
    /**
     * <code>string transaction_id = 14 [json_name = "transactionId"];</code>
     * @return The transactionId.
     */
    public java.lang.String getTransactionId() {
      java.lang.Object ref = transactionId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        transactionId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string transaction_id = 14 [json_name = "transactionId"];</code>
     * @return The bytes for transactionId.
     */
    public com.google.protobuf.ByteString
        getTransactionIdBytes() {
      java.lang.Object ref = transactionId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        transactionId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string transaction_id = 14 [json_name = "transactionId"];</code>
     * @param value The transactionId to set.
     * @return This builder for chaining.
     */
    public Builder setTransactionId(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      transactionId_ = value;
      bitField0_ |= 0x00002000;
      onChanged();
      return this;
    }
    /**
     * <code>string transaction_id = 14 [json_name = "transactionId"];</code>
     * @return This builder for chaining.
     */
    public Builder clearTransactionId() {
      transactionId_ = getDefaultInstance().getTransactionId();
      bitField0_ = (bitField0_ & ~0x00002000);
      onChanged();
      return this;
    }
    /**
     * <code>string transaction_id = 14 [json_name = "transactionId"];</code>
     * @param value The bytes for transactionId to set.
     * @return This builder for chaining.
     */
    public Builder setTransactionIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      transactionId_ = value;
      bitField0_ |= 0x00002000;
      onChanged();
      return this;
    }

    private boolean claimable_ ;
    /**
     * <code>bool claimable = 15 [json_name = "claimable"];</code>
     * @return The claimable.
     */
    @java.lang.Override
    public boolean getClaimable() {
      return claimable_;
    }
    /**
     * <code>bool claimable = 15 [json_name = "claimable"];</code>
     * @param value The claimable to set.
     * @return This builder for chaining.
     */
    public Builder setClaimable(boolean value) {

      claimable_ = value;
      bitField0_ |= 0x00004000;
      onChanged();
      return this;
    }
    /**
     * <code>bool claimable = 15 [json_name = "claimable"];</code>
     * @return This builder for chaining.
     */
    public Builder clearClaimable() {
      bitField0_ = (bitField0_ & ~0x00004000);
      claimable_ = false;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:game_engine.commission.v1.RebetClaimMsg)
  }

  // @@protoc_insertion_point(class_scope:game_engine.commission.v1.RebetClaimMsg)
  private static final com.game_engine.commission.v1.RebetClaimMsg DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.game_engine.commission.v1.RebetClaimMsg();
  }

  public static com.game_engine.commission.v1.RebetClaimMsg getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<RebetClaimMsg>
      PARSER = new com.google.protobuf.AbstractParser<RebetClaimMsg>() {
    @java.lang.Override
    public RebetClaimMsg parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<RebetClaimMsg> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<RebetClaimMsg> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.game_engine.commission.v1.RebetClaimMsg getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

