// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: commission/v1/commission_service.proto

// Protobuf Java Version: 3.25.3
package com.game_engine.commission.v1;

public interface UpdateRebetProgressRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:game_engine.commission.v1.UpdateRebetProgressRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int64 id = 1 [json_name = "id"];</code>
   * @return The id.
   */
  long getId();

  /**
   * <code>double additional_bet_amount = 2 [json_name = "additionalBetAmount"];</code>
   * @return The additionalBetAmount.
   */
  double getAdditionalBetAmount();
}
