// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: commission/v1/commission_service.proto

// Protobuf Java Version: 3.25.3
package com.game_engine.commission.v1;

public interface UpdateCommissionConfigRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:game_engine.commission.v1.UpdateCommissionConfigRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int64 id = 1 [json_name = "id"];</code>
   * @return The id.
   */
  long getId();

  /**
   * <code>.game_engine.commission.v1.CommissionConfig config = 2 [json_name = "config"];</code>
   * @return Whether the config field is set.
   */
  boolean hasConfig();
  /**
   * <code>.game_engine.commission.v1.CommissionConfig config = 2 [json_name = "config"];</code>
   * @return The config.
   */
  com.game_engine.commission.v1.CommissionConfig getConfig();
  /**
   * <code>.game_engine.commission.v1.CommissionConfig config = 2 [json_name = "config"];</code>
   */
  com.game_engine.commission.v1.CommissionConfigOrBuilder getConfigOrBuilder();
}
