server:
  port: 9035

grpc:
  server:
    port: 9015
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/commission_db
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: update
