server:
  port: 9034

grpc:
  server:
    port: 9013

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/bonus_db
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: update

management:
  endpoints:
    web:
      exposure:
        include: health
