// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: payment/v1/payment_service.proto

// Protobuf Java Version: 3.25.3
package com.game_engine.payment.v1;

public interface CreateDepositRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:game_engine.payment.v1.CreateDepositRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string user_id = 1 [json_name = "userId"];</code>
   * @return The userId.
   */
  java.lang.String getUserId();
  /**
   * <code>string user_id = 1 [json_name = "userId"];</code>
   * @return The bytes for userId.
   */
  com.google.protobuf.ByteString
      getUserIdBytes();

  /**
   * <code>double amount = 2 [json_name = "amount"];</code>
   * @return The amount.
   */
  double getAmount();

  /**
   * <code>string method = 3 [json_name = "method"];</code>
   * @return The method.
   */
  java.lang.String getMethod();
  /**
   * <code>string method = 3 [json_name = "method"];</code>
   * @return The bytes for method.
   */
  com.google.protobuf.ByteString
      getMethodBytes();

  /**
   * <code>string currency = 4 [json_name = "currency"];</code>
   * @return The currency.
   */
  java.lang.String getCurrency();
  /**
   * <code>string currency = 4 [json_name = "currency"];</code>
   * @return The bytes for currency.
   */
  com.google.protobuf.ByteString
      getCurrencyBytes();

  /**
   * <code>string description = 5 [json_name = "description"];</code>
   * @return The description.
   */
  java.lang.String getDescription();
  /**
   * <code>string description = 5 [json_name = "description"];</code>
   * @return The bytes for description.
   */
  com.google.protobuf.ByteString
      getDescriptionBytes();
}
