server:
  port: 9036

grpc:
  server:
    port: 9014
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/affiliate_db
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: update
