// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: affiliate/v1/affiliate_service.proto

// Protobuf Java Version: 3.25.3
package com.game_engine.affiliate.v1;

/**
 * Protobuf type {@code game_engine.affiliate.v1.GetActiveAffiliatesResponse}
 */
public final class GetActiveAffiliatesResponse extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:game_engine.affiliate.v1.GetActiveAffiliatesResponse)
    GetActiveAffiliatesResponseOrBuilder {
private static final long serialVersionUID = 0L;
  // Use GetActiveAffiliatesResponse.newBuilder() to construct.
  private GetActiveAffiliatesResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private GetActiveAffiliatesResponse() {
    affiliates_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new GetActiveAffiliatesResponse();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.game_engine.affiliate.v1.AffiliateServiceOuterClass.internal_static_game_engine_affiliate_v1_GetActiveAffiliatesResponse_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.game_engine.affiliate.v1.AffiliateServiceOuterClass.internal_static_game_engine_affiliate_v1_GetActiveAffiliatesResponse_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.game_engine.affiliate.v1.GetActiveAffiliatesResponse.class, com.game_engine.affiliate.v1.GetActiveAffiliatesResponse.Builder.class);
  }

  public static final int AFFILIATES_FIELD_NUMBER = 1;
  @SuppressWarnings("serial")
  private java.util.List<com.game_engine.affiliate.v1.Affiliate> affiliates_;
  /**
   * <code>repeated .game_engine.affiliate.v1.Affiliate affiliates = 1 [json_name = "affiliates"];</code>
   */
  @java.lang.Override
  public java.util.List<com.game_engine.affiliate.v1.Affiliate> getAffiliatesList() {
    return affiliates_;
  }
  /**
   * <code>repeated .game_engine.affiliate.v1.Affiliate affiliates = 1 [json_name = "affiliates"];</code>
   */
  @java.lang.Override
  public java.util.List<? extends com.game_engine.affiliate.v1.AffiliateOrBuilder> 
      getAffiliatesOrBuilderList() {
    return affiliates_;
  }
  /**
   * <code>repeated .game_engine.affiliate.v1.Affiliate affiliates = 1 [json_name = "affiliates"];</code>
   */
  @java.lang.Override
  public int getAffiliatesCount() {
    return affiliates_.size();
  }
  /**
   * <code>repeated .game_engine.affiliate.v1.Affiliate affiliates = 1 [json_name = "affiliates"];</code>
   */
  @java.lang.Override
  public com.game_engine.affiliate.v1.Affiliate getAffiliates(int index) {
    return affiliates_.get(index);
  }
  /**
   * <code>repeated .game_engine.affiliate.v1.Affiliate affiliates = 1 [json_name = "affiliates"];</code>
   */
  @java.lang.Override
  public com.game_engine.affiliate.v1.AffiliateOrBuilder getAffiliatesOrBuilder(
      int index) {
    return affiliates_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    for (int i = 0; i < affiliates_.size(); i++) {
      output.writeMessage(1, affiliates_.get(i));
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    for (int i = 0; i < affiliates_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, affiliates_.get(i));
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.game_engine.affiliate.v1.GetActiveAffiliatesResponse)) {
      return super.equals(obj);
    }
    com.game_engine.affiliate.v1.GetActiveAffiliatesResponse other = (com.game_engine.affiliate.v1.GetActiveAffiliatesResponse) obj;

    if (!getAffiliatesList()
        .equals(other.getAffiliatesList())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (getAffiliatesCount() > 0) {
      hash = (37 * hash) + AFFILIATES_FIELD_NUMBER;
      hash = (53 * hash) + getAffiliatesList().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.game_engine.affiliate.v1.GetActiveAffiliatesResponse parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.game_engine.affiliate.v1.GetActiveAffiliatesResponse parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.game_engine.affiliate.v1.GetActiveAffiliatesResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.game_engine.affiliate.v1.GetActiveAffiliatesResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.game_engine.affiliate.v1.GetActiveAffiliatesResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.game_engine.affiliate.v1.GetActiveAffiliatesResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.game_engine.affiliate.v1.GetActiveAffiliatesResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.game_engine.affiliate.v1.GetActiveAffiliatesResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static com.game_engine.affiliate.v1.GetActiveAffiliatesResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static com.game_engine.affiliate.v1.GetActiveAffiliatesResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.game_engine.affiliate.v1.GetActiveAffiliatesResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.game_engine.affiliate.v1.GetActiveAffiliatesResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.game_engine.affiliate.v1.GetActiveAffiliatesResponse prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code game_engine.affiliate.v1.GetActiveAffiliatesResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:game_engine.affiliate.v1.GetActiveAffiliatesResponse)
      com.game_engine.affiliate.v1.GetActiveAffiliatesResponseOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.game_engine.affiliate.v1.AffiliateServiceOuterClass.internal_static_game_engine_affiliate_v1_GetActiveAffiliatesResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.game_engine.affiliate.v1.AffiliateServiceOuterClass.internal_static_game_engine_affiliate_v1_GetActiveAffiliatesResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.game_engine.affiliate.v1.GetActiveAffiliatesResponse.class, com.game_engine.affiliate.v1.GetActiveAffiliatesResponse.Builder.class);
    }

    // Construct using com.game_engine.affiliate.v1.GetActiveAffiliatesResponse.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      if (affiliatesBuilder_ == null) {
        affiliates_ = java.util.Collections.emptyList();
      } else {
        affiliates_ = null;
        affiliatesBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000001);
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.game_engine.affiliate.v1.AffiliateServiceOuterClass.internal_static_game_engine_affiliate_v1_GetActiveAffiliatesResponse_descriptor;
    }

    @java.lang.Override
    public com.game_engine.affiliate.v1.GetActiveAffiliatesResponse getDefaultInstanceForType() {
      return com.game_engine.affiliate.v1.GetActiveAffiliatesResponse.getDefaultInstance();
    }

    @java.lang.Override
    public com.game_engine.affiliate.v1.GetActiveAffiliatesResponse build() {
      com.game_engine.affiliate.v1.GetActiveAffiliatesResponse result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.game_engine.affiliate.v1.GetActiveAffiliatesResponse buildPartial() {
      com.game_engine.affiliate.v1.GetActiveAffiliatesResponse result = new com.game_engine.affiliate.v1.GetActiveAffiliatesResponse(this);
      buildPartialRepeatedFields(result);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartialRepeatedFields(com.game_engine.affiliate.v1.GetActiveAffiliatesResponse result) {
      if (affiliatesBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0)) {
          affiliates_ = java.util.Collections.unmodifiableList(affiliates_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.affiliates_ = affiliates_;
      } else {
        result.affiliates_ = affiliatesBuilder_.build();
      }
    }

    private void buildPartial0(com.game_engine.affiliate.v1.GetActiveAffiliatesResponse result) {
      int from_bitField0_ = bitField0_;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.game_engine.affiliate.v1.GetActiveAffiliatesResponse) {
        return mergeFrom((com.game_engine.affiliate.v1.GetActiveAffiliatesResponse)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.game_engine.affiliate.v1.GetActiveAffiliatesResponse other) {
      if (other == com.game_engine.affiliate.v1.GetActiveAffiliatesResponse.getDefaultInstance()) return this;
      if (affiliatesBuilder_ == null) {
        if (!other.affiliates_.isEmpty()) {
          if (affiliates_.isEmpty()) {
            affiliates_ = other.affiliates_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureAffiliatesIsMutable();
            affiliates_.addAll(other.affiliates_);
          }
          onChanged();
        }
      } else {
        if (!other.affiliates_.isEmpty()) {
          if (affiliatesBuilder_.isEmpty()) {
            affiliatesBuilder_.dispose();
            affiliatesBuilder_ = null;
            affiliates_ = other.affiliates_;
            bitField0_ = (bitField0_ & ~0x00000001);
            affiliatesBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getAffiliatesFieldBuilder() : null;
          } else {
            affiliatesBuilder_.addAllMessages(other.affiliates_);
          }
        }
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              com.game_engine.affiliate.v1.Affiliate m =
                  input.readMessage(
                      com.game_engine.affiliate.v1.Affiliate.parser(),
                      extensionRegistry);
              if (affiliatesBuilder_ == null) {
                ensureAffiliatesIsMutable();
                affiliates_.add(m);
              } else {
                affiliatesBuilder_.addMessage(m);
              }
              break;
            } // case 10
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private java.util.List<com.game_engine.affiliate.v1.Affiliate> affiliates_ =
      java.util.Collections.emptyList();
    private void ensureAffiliatesIsMutable() {
      if (!((bitField0_ & 0x00000001) != 0)) {
        affiliates_ = new java.util.ArrayList<com.game_engine.affiliate.v1.Affiliate>(affiliates_);
        bitField0_ |= 0x00000001;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.game_engine.affiliate.v1.Affiliate, com.game_engine.affiliate.v1.Affiliate.Builder, com.game_engine.affiliate.v1.AffiliateOrBuilder> affiliatesBuilder_;

    /**
     * <code>repeated .game_engine.affiliate.v1.Affiliate affiliates = 1 [json_name = "affiliates"];</code>
     */
    public java.util.List<com.game_engine.affiliate.v1.Affiliate> getAffiliatesList() {
      if (affiliatesBuilder_ == null) {
        return java.util.Collections.unmodifiableList(affiliates_);
      } else {
        return affiliatesBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .game_engine.affiliate.v1.Affiliate affiliates = 1 [json_name = "affiliates"];</code>
     */
    public int getAffiliatesCount() {
      if (affiliatesBuilder_ == null) {
        return affiliates_.size();
      } else {
        return affiliatesBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .game_engine.affiliate.v1.Affiliate affiliates = 1 [json_name = "affiliates"];</code>
     */
    public com.game_engine.affiliate.v1.Affiliate getAffiliates(int index) {
      if (affiliatesBuilder_ == null) {
        return affiliates_.get(index);
      } else {
        return affiliatesBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .game_engine.affiliate.v1.Affiliate affiliates = 1 [json_name = "affiliates"];</code>
     */
    public Builder setAffiliates(
        int index, com.game_engine.affiliate.v1.Affiliate value) {
      if (affiliatesBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureAffiliatesIsMutable();
        affiliates_.set(index, value);
        onChanged();
      } else {
        affiliatesBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .game_engine.affiliate.v1.Affiliate affiliates = 1 [json_name = "affiliates"];</code>
     */
    public Builder setAffiliates(
        int index, com.game_engine.affiliate.v1.Affiliate.Builder builderForValue) {
      if (affiliatesBuilder_ == null) {
        ensureAffiliatesIsMutable();
        affiliates_.set(index, builderForValue.build());
        onChanged();
      } else {
        affiliatesBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .game_engine.affiliate.v1.Affiliate affiliates = 1 [json_name = "affiliates"];</code>
     */
    public Builder addAffiliates(com.game_engine.affiliate.v1.Affiliate value) {
      if (affiliatesBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureAffiliatesIsMutable();
        affiliates_.add(value);
        onChanged();
      } else {
        affiliatesBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .game_engine.affiliate.v1.Affiliate affiliates = 1 [json_name = "affiliates"];</code>
     */
    public Builder addAffiliates(
        int index, com.game_engine.affiliate.v1.Affiliate value) {
      if (affiliatesBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureAffiliatesIsMutable();
        affiliates_.add(index, value);
        onChanged();
      } else {
        affiliatesBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .game_engine.affiliate.v1.Affiliate affiliates = 1 [json_name = "affiliates"];</code>
     */
    public Builder addAffiliates(
        com.game_engine.affiliate.v1.Affiliate.Builder builderForValue) {
      if (affiliatesBuilder_ == null) {
        ensureAffiliatesIsMutable();
        affiliates_.add(builderForValue.build());
        onChanged();
      } else {
        affiliatesBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .game_engine.affiliate.v1.Affiliate affiliates = 1 [json_name = "affiliates"];</code>
     */
    public Builder addAffiliates(
        int index, com.game_engine.affiliate.v1.Affiliate.Builder builderForValue) {
      if (affiliatesBuilder_ == null) {
        ensureAffiliatesIsMutable();
        affiliates_.add(index, builderForValue.build());
        onChanged();
      } else {
        affiliatesBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .game_engine.affiliate.v1.Affiliate affiliates = 1 [json_name = "affiliates"];</code>
     */
    public Builder addAllAffiliates(
        java.lang.Iterable<? extends com.game_engine.affiliate.v1.Affiliate> values) {
      if (affiliatesBuilder_ == null) {
        ensureAffiliatesIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, affiliates_);
        onChanged();
      } else {
        affiliatesBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .game_engine.affiliate.v1.Affiliate affiliates = 1 [json_name = "affiliates"];</code>
     */
    public Builder clearAffiliates() {
      if (affiliatesBuilder_ == null) {
        affiliates_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
      } else {
        affiliatesBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .game_engine.affiliate.v1.Affiliate affiliates = 1 [json_name = "affiliates"];</code>
     */
    public Builder removeAffiliates(int index) {
      if (affiliatesBuilder_ == null) {
        ensureAffiliatesIsMutable();
        affiliates_.remove(index);
        onChanged();
      } else {
        affiliatesBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .game_engine.affiliate.v1.Affiliate affiliates = 1 [json_name = "affiliates"];</code>
     */
    public com.game_engine.affiliate.v1.Affiliate.Builder getAffiliatesBuilder(
        int index) {
      return getAffiliatesFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .game_engine.affiliate.v1.Affiliate affiliates = 1 [json_name = "affiliates"];</code>
     */
    public com.game_engine.affiliate.v1.AffiliateOrBuilder getAffiliatesOrBuilder(
        int index) {
      if (affiliatesBuilder_ == null) {
        return affiliates_.get(index);  } else {
        return affiliatesBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .game_engine.affiliate.v1.Affiliate affiliates = 1 [json_name = "affiliates"];</code>
     */
    public java.util.List<? extends com.game_engine.affiliate.v1.AffiliateOrBuilder> 
         getAffiliatesOrBuilderList() {
      if (affiliatesBuilder_ != null) {
        return affiliatesBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(affiliates_);
      }
    }
    /**
     * <code>repeated .game_engine.affiliate.v1.Affiliate affiliates = 1 [json_name = "affiliates"];</code>
     */
    public com.game_engine.affiliate.v1.Affiliate.Builder addAffiliatesBuilder() {
      return getAffiliatesFieldBuilder().addBuilder(
          com.game_engine.affiliate.v1.Affiliate.getDefaultInstance());
    }
    /**
     * <code>repeated .game_engine.affiliate.v1.Affiliate affiliates = 1 [json_name = "affiliates"];</code>
     */
    public com.game_engine.affiliate.v1.Affiliate.Builder addAffiliatesBuilder(
        int index) {
      return getAffiliatesFieldBuilder().addBuilder(
          index, com.game_engine.affiliate.v1.Affiliate.getDefaultInstance());
    }
    /**
     * <code>repeated .game_engine.affiliate.v1.Affiliate affiliates = 1 [json_name = "affiliates"];</code>
     */
    public java.util.List<com.game_engine.affiliate.v1.Affiliate.Builder> 
         getAffiliatesBuilderList() {
      return getAffiliatesFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.game_engine.affiliate.v1.Affiliate, com.game_engine.affiliate.v1.Affiliate.Builder, com.game_engine.affiliate.v1.AffiliateOrBuilder> 
        getAffiliatesFieldBuilder() {
      if (affiliatesBuilder_ == null) {
        affiliatesBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            com.game_engine.affiliate.v1.Affiliate, com.game_engine.affiliate.v1.Affiliate.Builder, com.game_engine.affiliate.v1.AffiliateOrBuilder>(
                affiliates_,
                ((bitField0_ & 0x00000001) != 0),
                getParentForChildren(),
                isClean());
        affiliates_ = null;
      }
      return affiliatesBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:game_engine.affiliate.v1.GetActiveAffiliatesResponse)
  }

  // @@protoc_insertion_point(class_scope:game_engine.affiliate.v1.GetActiveAffiliatesResponse)
  private static final com.game_engine.affiliate.v1.GetActiveAffiliatesResponse DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.game_engine.affiliate.v1.GetActiveAffiliatesResponse();
  }

  public static com.game_engine.affiliate.v1.GetActiveAffiliatesResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<GetActiveAffiliatesResponse>
      PARSER = new com.google.protobuf.AbstractParser<GetActiveAffiliatesResponse>() {
    @java.lang.Override
    public GetActiveAffiliatesResponse parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<GetActiveAffiliatesResponse> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<GetActiveAffiliatesResponse> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.game_engine.affiliate.v1.GetActiveAffiliatesResponse getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

