// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: affiliate/v1/affiliate_service.proto

// Protobuf Java Version: 3.25.3
package com.game_engine.affiliate.v1;

public interface GetAffiliateStatsResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:game_engine.affiliate.v1.GetAffiliateStatsResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int64 total_clicks = 1 [json_name = "totalClicks"];</code>
   * @return The totalClicks.
   */
  long getTotalClicks();

  /**
   * <code>int64 total_registrations = 2 [json_name = "totalRegistrations"];</code>
   * @return The totalRegistrations.
   */
  long getTotalRegistrations();

  /**
   * <code>int64 total_depositors = 3 [json_name = "totalDepositors"];</code>
   * @return The totalDepositors.
   */
  long getTotalDepositors();

  /**
   * <code>double total_revenue = 4 [json_name = "totalRevenue"];</code>
   * @return The totalRevenue.
   */
  double getTotalRevenue();

  /**
   * <code>double total_commission = 5 [json_name = "totalCommission"];</code>
   * @return The totalCommission.
   */
  double getTotalCommission();
}
