// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: affiliate/v1/affiliate_service.proto

// Protobuf Java Version: 3.25.3
package com.game_engine.affiliate.v1;

public interface GetCampaignReferralsResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:game_engine.affiliate.v1.GetCampaignReferralsResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .game_engine.affiliate.v1.Referral referrals = 1 [json_name = "referrals"];</code>
   */
  java.util.List<com.game_engine.affiliate.v1.Referral> 
      getReferralsList();
  /**
   * <code>repeated .game_engine.affiliate.v1.Referral referrals = 1 [json_name = "referrals"];</code>
   */
  com.game_engine.affiliate.v1.Referral getReferrals(int index);
  /**
   * <code>repeated .game_engine.affiliate.v1.Referral referrals = 1 [json_name = "referrals"];</code>
   */
  int getReferralsCount();
  /**
   * <code>repeated .game_engine.affiliate.v1.Referral referrals = 1 [json_name = "referrals"];</code>
   */
  java.util.List<? extends com.game_engine.affiliate.v1.ReferralOrBuilder> 
      getReferralsOrBuilderList();
  /**
   * <code>repeated .game_engine.affiliate.v1.Referral referrals = 1 [json_name = "referrals"];</code>
   */
  com.game_engine.affiliate.v1.ReferralOrBuilder getReferralsOrBuilder(
      int index);
}
