// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: affiliate/v1/affiliate_service.proto

// Protobuf Java Version: 3.25.3
package com.game_engine.affiliate.v1;

/**
 * Protobuf type {@code game_engine.affiliate.v1.GetSubAffiliatesResponse}
 */
public final class GetSubAffiliatesResponse extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:game_engine.affiliate.v1.GetSubAffiliatesResponse)
    GetSubAffiliatesResponseOrBuilder {
private static final long serialVersionUID = 0L;
  // Use GetSubAffiliatesResponse.newBuilder() to construct.
  private GetSubAffiliatesResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private GetSubAffiliatesResponse() {
    subAffiliates_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new GetSubAffiliatesResponse();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.game_engine.affiliate.v1.AffiliateServiceOuterClass.internal_static_game_engine_affiliate_v1_GetSubAffiliatesResponse_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.game_engine.affiliate.v1.AffiliateServiceOuterClass.internal_static_game_engine_affiliate_v1_GetSubAffiliatesResponse_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.game_engine.affiliate.v1.GetSubAffiliatesResponse.class, com.game_engine.affiliate.v1.GetSubAffiliatesResponse.Builder.class);
  }

  public static final int SUB_AFFILIATES_FIELD_NUMBER = 1;
  @SuppressWarnings("serial")
  private java.util.List<com.game_engine.affiliate.v1.Affiliate> subAffiliates_;
  /**
   * <code>repeated .game_engine.affiliate.v1.Affiliate sub_affiliates = 1 [json_name = "subAffiliates"];</code>
   */
  @java.lang.Override
  public java.util.List<com.game_engine.affiliate.v1.Affiliate> getSubAffiliatesList() {
    return subAffiliates_;
  }
  /**
   * <code>repeated .game_engine.affiliate.v1.Affiliate sub_affiliates = 1 [json_name = "subAffiliates"];</code>
   */
  @java.lang.Override
  public java.util.List<? extends com.game_engine.affiliate.v1.AffiliateOrBuilder> 
      getSubAffiliatesOrBuilderList() {
    return subAffiliates_;
  }
  /**
   * <code>repeated .game_engine.affiliate.v1.Affiliate sub_affiliates = 1 [json_name = "subAffiliates"];</code>
   */
  @java.lang.Override
  public int getSubAffiliatesCount() {
    return subAffiliates_.size();
  }
  /**
   * <code>repeated .game_engine.affiliate.v1.Affiliate sub_affiliates = 1 [json_name = "subAffiliates"];</code>
   */
  @java.lang.Override
  public com.game_engine.affiliate.v1.Affiliate getSubAffiliates(int index) {
    return subAffiliates_.get(index);
  }
  /**
   * <code>repeated .game_engine.affiliate.v1.Affiliate sub_affiliates = 1 [json_name = "subAffiliates"];</code>
   */
  @java.lang.Override
  public com.game_engine.affiliate.v1.AffiliateOrBuilder getSubAffiliatesOrBuilder(
      int index) {
    return subAffiliates_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    for (int i = 0; i < subAffiliates_.size(); i++) {
      output.writeMessage(1, subAffiliates_.get(i));
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    for (int i = 0; i < subAffiliates_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, subAffiliates_.get(i));
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.game_engine.affiliate.v1.GetSubAffiliatesResponse)) {
      return super.equals(obj);
    }
    com.game_engine.affiliate.v1.GetSubAffiliatesResponse other = (com.game_engine.affiliate.v1.GetSubAffiliatesResponse) obj;

    if (!getSubAffiliatesList()
        .equals(other.getSubAffiliatesList())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (getSubAffiliatesCount() > 0) {
      hash = (37 * hash) + SUB_AFFILIATES_FIELD_NUMBER;
      hash = (53 * hash) + getSubAffiliatesList().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.game_engine.affiliate.v1.GetSubAffiliatesResponse parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.game_engine.affiliate.v1.GetSubAffiliatesResponse parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.game_engine.affiliate.v1.GetSubAffiliatesResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.game_engine.affiliate.v1.GetSubAffiliatesResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.game_engine.affiliate.v1.GetSubAffiliatesResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.game_engine.affiliate.v1.GetSubAffiliatesResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.game_engine.affiliate.v1.GetSubAffiliatesResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.game_engine.affiliate.v1.GetSubAffiliatesResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static com.game_engine.affiliate.v1.GetSubAffiliatesResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static com.game_engine.affiliate.v1.GetSubAffiliatesResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.game_engine.affiliate.v1.GetSubAffiliatesResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.game_engine.affiliate.v1.GetSubAffiliatesResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.game_engine.affiliate.v1.GetSubAffiliatesResponse prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code game_engine.affiliate.v1.GetSubAffiliatesResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:game_engine.affiliate.v1.GetSubAffiliatesResponse)
      com.game_engine.affiliate.v1.GetSubAffiliatesResponseOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.game_engine.affiliate.v1.AffiliateServiceOuterClass.internal_static_game_engine_affiliate_v1_GetSubAffiliatesResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.game_engine.affiliate.v1.AffiliateServiceOuterClass.internal_static_game_engine_affiliate_v1_GetSubAffiliatesResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.game_engine.affiliate.v1.GetSubAffiliatesResponse.class, com.game_engine.affiliate.v1.GetSubAffiliatesResponse.Builder.class);
    }

    // Construct using com.game_engine.affiliate.v1.GetSubAffiliatesResponse.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      if (subAffiliatesBuilder_ == null) {
        subAffiliates_ = java.util.Collections.emptyList();
      } else {
        subAffiliates_ = null;
        subAffiliatesBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000001);
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.game_engine.affiliate.v1.AffiliateServiceOuterClass.internal_static_game_engine_affiliate_v1_GetSubAffiliatesResponse_descriptor;
    }

    @java.lang.Override
    public com.game_engine.affiliate.v1.GetSubAffiliatesResponse getDefaultInstanceForType() {
      return com.game_engine.affiliate.v1.GetSubAffiliatesResponse.getDefaultInstance();
    }

    @java.lang.Override
    public com.game_engine.affiliate.v1.GetSubAffiliatesResponse build() {
      com.game_engine.affiliate.v1.GetSubAffiliatesResponse result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.game_engine.affiliate.v1.GetSubAffiliatesResponse buildPartial() {
      com.game_engine.affiliate.v1.GetSubAffiliatesResponse result = new com.game_engine.affiliate.v1.GetSubAffiliatesResponse(this);
      buildPartialRepeatedFields(result);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartialRepeatedFields(com.game_engine.affiliate.v1.GetSubAffiliatesResponse result) {
      if (subAffiliatesBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0)) {
          subAffiliates_ = java.util.Collections.unmodifiableList(subAffiliates_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.subAffiliates_ = subAffiliates_;
      } else {
        result.subAffiliates_ = subAffiliatesBuilder_.build();
      }
    }

    private void buildPartial0(com.game_engine.affiliate.v1.GetSubAffiliatesResponse result) {
      int from_bitField0_ = bitField0_;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.game_engine.affiliate.v1.GetSubAffiliatesResponse) {
        return mergeFrom((com.game_engine.affiliate.v1.GetSubAffiliatesResponse)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.game_engine.affiliate.v1.GetSubAffiliatesResponse other) {
      if (other == com.game_engine.affiliate.v1.GetSubAffiliatesResponse.getDefaultInstance()) return this;
      if (subAffiliatesBuilder_ == null) {
        if (!other.subAffiliates_.isEmpty()) {
          if (subAffiliates_.isEmpty()) {
            subAffiliates_ = other.subAffiliates_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureSubAffiliatesIsMutable();
            subAffiliates_.addAll(other.subAffiliates_);
          }
          onChanged();
        }
      } else {
        if (!other.subAffiliates_.isEmpty()) {
          if (subAffiliatesBuilder_.isEmpty()) {
            subAffiliatesBuilder_.dispose();
            subAffiliatesBuilder_ = null;
            subAffiliates_ = other.subAffiliates_;
            bitField0_ = (bitField0_ & ~0x00000001);
            subAffiliatesBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getSubAffiliatesFieldBuilder() : null;
          } else {
            subAffiliatesBuilder_.addAllMessages(other.subAffiliates_);
          }
        }
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              com.game_engine.affiliate.v1.Affiliate m =
                  input.readMessage(
                      com.game_engine.affiliate.v1.Affiliate.parser(),
                      extensionRegistry);
              if (subAffiliatesBuilder_ == null) {
                ensureSubAffiliatesIsMutable();
                subAffiliates_.add(m);
              } else {
                subAffiliatesBuilder_.addMessage(m);
              }
              break;
            } // case 10
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private java.util.List<com.game_engine.affiliate.v1.Affiliate> subAffiliates_ =
      java.util.Collections.emptyList();
    private void ensureSubAffiliatesIsMutable() {
      if (!((bitField0_ & 0x00000001) != 0)) {
        subAffiliates_ = new java.util.ArrayList<com.game_engine.affiliate.v1.Affiliate>(subAffiliates_);
        bitField0_ |= 0x00000001;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.game_engine.affiliate.v1.Affiliate, com.game_engine.affiliate.v1.Affiliate.Builder, com.game_engine.affiliate.v1.AffiliateOrBuilder> subAffiliatesBuilder_;

    /**
     * <code>repeated .game_engine.affiliate.v1.Affiliate sub_affiliates = 1 [json_name = "subAffiliates"];</code>
     */
    public java.util.List<com.game_engine.affiliate.v1.Affiliate> getSubAffiliatesList() {
      if (subAffiliatesBuilder_ == null) {
        return java.util.Collections.unmodifiableList(subAffiliates_);
      } else {
        return subAffiliatesBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .game_engine.affiliate.v1.Affiliate sub_affiliates = 1 [json_name = "subAffiliates"];</code>
     */
    public int getSubAffiliatesCount() {
      if (subAffiliatesBuilder_ == null) {
        return subAffiliates_.size();
      } else {
        return subAffiliatesBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .game_engine.affiliate.v1.Affiliate sub_affiliates = 1 [json_name = "subAffiliates"];</code>
     */
    public com.game_engine.affiliate.v1.Affiliate getSubAffiliates(int index) {
      if (subAffiliatesBuilder_ == null) {
        return subAffiliates_.get(index);
      } else {
        return subAffiliatesBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .game_engine.affiliate.v1.Affiliate sub_affiliates = 1 [json_name = "subAffiliates"];</code>
     */
    public Builder setSubAffiliates(
        int index, com.game_engine.affiliate.v1.Affiliate value) {
      if (subAffiliatesBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureSubAffiliatesIsMutable();
        subAffiliates_.set(index, value);
        onChanged();
      } else {
        subAffiliatesBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .game_engine.affiliate.v1.Affiliate sub_affiliates = 1 [json_name = "subAffiliates"];</code>
     */
    public Builder setSubAffiliates(
        int index, com.game_engine.affiliate.v1.Affiliate.Builder builderForValue) {
      if (subAffiliatesBuilder_ == null) {
        ensureSubAffiliatesIsMutable();
        subAffiliates_.set(index, builderForValue.build());
        onChanged();
      } else {
        subAffiliatesBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .game_engine.affiliate.v1.Affiliate sub_affiliates = 1 [json_name = "subAffiliates"];</code>
     */
    public Builder addSubAffiliates(com.game_engine.affiliate.v1.Affiliate value) {
      if (subAffiliatesBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureSubAffiliatesIsMutable();
        subAffiliates_.add(value);
        onChanged();
      } else {
        subAffiliatesBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .game_engine.affiliate.v1.Affiliate sub_affiliates = 1 [json_name = "subAffiliates"];</code>
     */
    public Builder addSubAffiliates(
        int index, com.game_engine.affiliate.v1.Affiliate value) {
      if (subAffiliatesBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureSubAffiliatesIsMutable();
        subAffiliates_.add(index, value);
        onChanged();
      } else {
        subAffiliatesBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .game_engine.affiliate.v1.Affiliate sub_affiliates = 1 [json_name = "subAffiliates"];</code>
     */
    public Builder addSubAffiliates(
        com.game_engine.affiliate.v1.Affiliate.Builder builderForValue) {
      if (subAffiliatesBuilder_ == null) {
        ensureSubAffiliatesIsMutable();
        subAffiliates_.add(builderForValue.build());
        onChanged();
      } else {
        subAffiliatesBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .game_engine.affiliate.v1.Affiliate sub_affiliates = 1 [json_name = "subAffiliates"];</code>
     */
    public Builder addSubAffiliates(
        int index, com.game_engine.affiliate.v1.Affiliate.Builder builderForValue) {
      if (subAffiliatesBuilder_ == null) {
        ensureSubAffiliatesIsMutable();
        subAffiliates_.add(index, builderForValue.build());
        onChanged();
      } else {
        subAffiliatesBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .game_engine.affiliate.v1.Affiliate sub_affiliates = 1 [json_name = "subAffiliates"];</code>
     */
    public Builder addAllSubAffiliates(
        java.lang.Iterable<? extends com.game_engine.affiliate.v1.Affiliate> values) {
      if (subAffiliatesBuilder_ == null) {
        ensureSubAffiliatesIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, subAffiliates_);
        onChanged();
      } else {
        subAffiliatesBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .game_engine.affiliate.v1.Affiliate sub_affiliates = 1 [json_name = "subAffiliates"];</code>
     */
    public Builder clearSubAffiliates() {
      if (subAffiliatesBuilder_ == null) {
        subAffiliates_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
      } else {
        subAffiliatesBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .game_engine.affiliate.v1.Affiliate sub_affiliates = 1 [json_name = "subAffiliates"];</code>
     */
    public Builder removeSubAffiliates(int index) {
      if (subAffiliatesBuilder_ == null) {
        ensureSubAffiliatesIsMutable();
        subAffiliates_.remove(index);
        onChanged();
      } else {
        subAffiliatesBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .game_engine.affiliate.v1.Affiliate sub_affiliates = 1 [json_name = "subAffiliates"];</code>
     */
    public com.game_engine.affiliate.v1.Affiliate.Builder getSubAffiliatesBuilder(
        int index) {
      return getSubAffiliatesFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .game_engine.affiliate.v1.Affiliate sub_affiliates = 1 [json_name = "subAffiliates"];</code>
     */
    public com.game_engine.affiliate.v1.AffiliateOrBuilder getSubAffiliatesOrBuilder(
        int index) {
      if (subAffiliatesBuilder_ == null) {
        return subAffiliates_.get(index);  } else {
        return subAffiliatesBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .game_engine.affiliate.v1.Affiliate sub_affiliates = 1 [json_name = "subAffiliates"];</code>
     */
    public java.util.List<? extends com.game_engine.affiliate.v1.AffiliateOrBuilder> 
         getSubAffiliatesOrBuilderList() {
      if (subAffiliatesBuilder_ != null) {
        return subAffiliatesBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(subAffiliates_);
      }
    }
    /**
     * <code>repeated .game_engine.affiliate.v1.Affiliate sub_affiliates = 1 [json_name = "subAffiliates"];</code>
     */
    public com.game_engine.affiliate.v1.Affiliate.Builder addSubAffiliatesBuilder() {
      return getSubAffiliatesFieldBuilder().addBuilder(
          com.game_engine.affiliate.v1.Affiliate.getDefaultInstance());
    }
    /**
     * <code>repeated .game_engine.affiliate.v1.Affiliate sub_affiliates = 1 [json_name = "subAffiliates"];</code>
     */
    public com.game_engine.affiliate.v1.Affiliate.Builder addSubAffiliatesBuilder(
        int index) {
      return getSubAffiliatesFieldBuilder().addBuilder(
          index, com.game_engine.affiliate.v1.Affiliate.getDefaultInstance());
    }
    /**
     * <code>repeated .game_engine.affiliate.v1.Affiliate sub_affiliates = 1 [json_name = "subAffiliates"];</code>
     */
    public java.util.List<com.game_engine.affiliate.v1.Affiliate.Builder> 
         getSubAffiliatesBuilderList() {
      return getSubAffiliatesFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.game_engine.affiliate.v1.Affiliate, com.game_engine.affiliate.v1.Affiliate.Builder, com.game_engine.affiliate.v1.AffiliateOrBuilder> 
        getSubAffiliatesFieldBuilder() {
      if (subAffiliatesBuilder_ == null) {
        subAffiliatesBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            com.game_engine.affiliate.v1.Affiliate, com.game_engine.affiliate.v1.Affiliate.Builder, com.game_engine.affiliate.v1.AffiliateOrBuilder>(
                subAffiliates_,
                ((bitField0_ & 0x00000001) != 0),
                getParentForChildren(),
                isClean());
        subAffiliates_ = null;
      }
      return subAffiliatesBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:game_engine.affiliate.v1.GetSubAffiliatesResponse)
  }

  // @@protoc_insertion_point(class_scope:game_engine.affiliate.v1.GetSubAffiliatesResponse)
  private static final com.game_engine.affiliate.v1.GetSubAffiliatesResponse DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.game_engine.affiliate.v1.GetSubAffiliatesResponse();
  }

  public static com.game_engine.affiliate.v1.GetSubAffiliatesResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<GetSubAffiliatesResponse>
      PARSER = new com.google.protobuf.AbstractParser<GetSubAffiliatesResponse>() {
    @java.lang.Override
    public GetSubAffiliatesResponse parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<GetSubAffiliatesResponse> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<GetSubAffiliatesResponse> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.game_engine.affiliate.v1.GetSubAffiliatesResponse getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

