// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: affiliate/v1/affiliate_service.proto

// Protobuf Java Version: 3.25.3
package com.game_engine.affiliate.v1;

/**
 * <pre>
 * UpdateAffiliateTier
 * </pre>
 *
 * Protobuf type {@code game_engine.affiliate.v1.UpdateAffiliateTierRequest}
 */
public final class UpdateAffiliateTierRequest extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:game_engine.affiliate.v1.UpdateAffiliateTierRequest)
    UpdateAffiliateTierRequestOrBuilder {
private static final long serialVersionUID = 0L;
  // Use UpdateAffiliateTierRequest.newBuilder() to construct.
  private UpdateAffiliateTierRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private UpdateAffiliateTierRequest() {
    tier_ = "";
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new UpdateAffiliateTierRequest();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.game_engine.affiliate.v1.AffiliateServiceOuterClass.internal_static_game_engine_affiliate_v1_UpdateAffiliateTierRequest_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.game_engine.affiliate.v1.AffiliateServiceOuterClass.internal_static_game_engine_affiliate_v1_UpdateAffiliateTierRequest_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.game_engine.affiliate.v1.UpdateAffiliateTierRequest.class, com.game_engine.affiliate.v1.UpdateAffiliateTierRequest.Builder.class);
  }

  public static final int AFFILIATE_ID_FIELD_NUMBER = 1;
  private long affiliateId_ = 0L;
  /**
   * <code>int64 affiliate_id = 1 [json_name = "affiliateId"];</code>
   * @return The affiliateId.
   */
  @java.lang.Override
  public long getAffiliateId() {
    return affiliateId_;
  }

  public static final int TIER_FIELD_NUMBER = 2;
  @SuppressWarnings("serial")
  private volatile java.lang.Object tier_ = "";
  /**
   * <code>string tier = 2 [json_name = "tier"];</code>
   * @return The tier.
   */
  @java.lang.Override
  public java.lang.String getTier() {
    java.lang.Object ref = tier_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      tier_ = s;
      return s;
    }
  }
  /**
   * <code>string tier = 2 [json_name = "tier"];</code>
   * @return The bytes for tier.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getTierBytes() {
    java.lang.Object ref = tier_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      tier_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (affiliateId_ != 0L) {
      output.writeInt64(1, affiliateId_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(tier_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, tier_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (affiliateId_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(1, affiliateId_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(tier_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, tier_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.game_engine.affiliate.v1.UpdateAffiliateTierRequest)) {
      return super.equals(obj);
    }
    com.game_engine.affiliate.v1.UpdateAffiliateTierRequest other = (com.game_engine.affiliate.v1.UpdateAffiliateTierRequest) obj;

    if (getAffiliateId()
        != other.getAffiliateId()) return false;
    if (!getTier()
        .equals(other.getTier())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + AFFILIATE_ID_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getAffiliateId());
    hash = (37 * hash) + TIER_FIELD_NUMBER;
    hash = (53 * hash) + getTier().hashCode();
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.game_engine.affiliate.v1.UpdateAffiliateTierRequest parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.game_engine.affiliate.v1.UpdateAffiliateTierRequest parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.game_engine.affiliate.v1.UpdateAffiliateTierRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.game_engine.affiliate.v1.UpdateAffiliateTierRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.game_engine.affiliate.v1.UpdateAffiliateTierRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.game_engine.affiliate.v1.UpdateAffiliateTierRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.game_engine.affiliate.v1.UpdateAffiliateTierRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.game_engine.affiliate.v1.UpdateAffiliateTierRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static com.game_engine.affiliate.v1.UpdateAffiliateTierRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static com.game_engine.affiliate.v1.UpdateAffiliateTierRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.game_engine.affiliate.v1.UpdateAffiliateTierRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.game_engine.affiliate.v1.UpdateAffiliateTierRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.game_engine.affiliate.v1.UpdateAffiliateTierRequest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * UpdateAffiliateTier
   * </pre>
   *
   * Protobuf type {@code game_engine.affiliate.v1.UpdateAffiliateTierRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:game_engine.affiliate.v1.UpdateAffiliateTierRequest)
      com.game_engine.affiliate.v1.UpdateAffiliateTierRequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.game_engine.affiliate.v1.AffiliateServiceOuterClass.internal_static_game_engine_affiliate_v1_UpdateAffiliateTierRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.game_engine.affiliate.v1.AffiliateServiceOuterClass.internal_static_game_engine_affiliate_v1_UpdateAffiliateTierRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.game_engine.affiliate.v1.UpdateAffiliateTierRequest.class, com.game_engine.affiliate.v1.UpdateAffiliateTierRequest.Builder.class);
    }

    // Construct using com.game_engine.affiliate.v1.UpdateAffiliateTierRequest.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      affiliateId_ = 0L;
      tier_ = "";
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.game_engine.affiliate.v1.AffiliateServiceOuterClass.internal_static_game_engine_affiliate_v1_UpdateAffiliateTierRequest_descriptor;
    }

    @java.lang.Override
    public com.game_engine.affiliate.v1.UpdateAffiliateTierRequest getDefaultInstanceForType() {
      return com.game_engine.affiliate.v1.UpdateAffiliateTierRequest.getDefaultInstance();
    }

    @java.lang.Override
    public com.game_engine.affiliate.v1.UpdateAffiliateTierRequest build() {
      com.game_engine.affiliate.v1.UpdateAffiliateTierRequest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.game_engine.affiliate.v1.UpdateAffiliateTierRequest buildPartial() {
      com.game_engine.affiliate.v1.UpdateAffiliateTierRequest result = new com.game_engine.affiliate.v1.UpdateAffiliateTierRequest(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(com.game_engine.affiliate.v1.UpdateAffiliateTierRequest result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.affiliateId_ = affiliateId_;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.tier_ = tier_;
      }
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.game_engine.affiliate.v1.UpdateAffiliateTierRequest) {
        return mergeFrom((com.game_engine.affiliate.v1.UpdateAffiliateTierRequest)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.game_engine.affiliate.v1.UpdateAffiliateTierRequest other) {
      if (other == com.game_engine.affiliate.v1.UpdateAffiliateTierRequest.getDefaultInstance()) return this;
      if (other.getAffiliateId() != 0L) {
        setAffiliateId(other.getAffiliateId());
      }
      if (!other.getTier().isEmpty()) {
        tier_ = other.tier_;
        bitField0_ |= 0x00000002;
        onChanged();
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              affiliateId_ = input.readInt64();
              bitField0_ |= 0x00000001;
              break;
            } // case 8
            case 18: {
              tier_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000002;
              break;
            } // case 18
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private long affiliateId_ ;
    /**
     * <code>int64 affiliate_id = 1 [json_name = "affiliateId"];</code>
     * @return The affiliateId.
     */
    @java.lang.Override
    public long getAffiliateId() {
      return affiliateId_;
    }
    /**
     * <code>int64 affiliate_id = 1 [json_name = "affiliateId"];</code>
     * @param value The affiliateId to set.
     * @return This builder for chaining.
     */
    public Builder setAffiliateId(long value) {

      affiliateId_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>int64 affiliate_id = 1 [json_name = "affiliateId"];</code>
     * @return This builder for chaining.
     */
    public Builder clearAffiliateId() {
      bitField0_ = (bitField0_ & ~0x00000001);
      affiliateId_ = 0L;
      onChanged();
      return this;
    }

    private java.lang.Object tier_ = "";
    /**
     * <code>string tier = 2 [json_name = "tier"];</code>
     * @return The tier.
     */
    public java.lang.String getTier() {
      java.lang.Object ref = tier_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        tier_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string tier = 2 [json_name = "tier"];</code>
     * @return The bytes for tier.
     */
    public com.google.protobuf.ByteString
        getTierBytes() {
      java.lang.Object ref = tier_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        tier_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string tier = 2 [json_name = "tier"];</code>
     * @param value The tier to set.
     * @return This builder for chaining.
     */
    public Builder setTier(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      tier_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>string tier = 2 [json_name = "tier"];</code>
     * @return This builder for chaining.
     */
    public Builder clearTier() {
      tier_ = getDefaultInstance().getTier();
      bitField0_ = (bitField0_ & ~0x00000002);
      onChanged();
      return this;
    }
    /**
     * <code>string tier = 2 [json_name = "tier"];</code>
     * @param value The bytes for tier to set.
     * @return This builder for chaining.
     */
    public Builder setTierBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      tier_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:game_engine.affiliate.v1.UpdateAffiliateTierRequest)
  }

  // @@protoc_insertion_point(class_scope:game_engine.affiliate.v1.UpdateAffiliateTierRequest)
  private static final com.game_engine.affiliate.v1.UpdateAffiliateTierRequest DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.game_engine.affiliate.v1.UpdateAffiliateTierRequest();
  }

  public static com.game_engine.affiliate.v1.UpdateAffiliateTierRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<UpdateAffiliateTierRequest>
      PARSER = new com.google.protobuf.AbstractParser<UpdateAffiliateTierRequest>() {
    @java.lang.Override
    public UpdateAffiliateTierRequest parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<UpdateAffiliateTierRequest> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<UpdateAffiliateTierRequest> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.game_engine.affiliate.v1.UpdateAffiliateTierRequest getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

